### ISSUE TITLE
Add Wit's End 

### ISSUE THREAD

**Issue by Timothee38** [OvercastNetwork/Rotations#212]
I just talked with a French Team (Orpheus) and they really enjoyed playing wit's end, so they ask me to create an issue here.
In my opinion, we could give it a few tests on public servers eventually and get some ratings.

**Comment by TiTo-418** [comment]
Re-Open this please. thanks

**Comment by Superjd10** [comment]
It was removed due to lack of defense and a lot (more than usual) of block spamming.

**Comment by TiTo-418** [comment]
Yeah, i know, but the next tournament is CTW and why not put in the rotations. Only is a idea :)

**Comment by Superjd10** [comment]
It's not needed. Where did you read it will be CTW? Adding tournament designed maps to public servers isn't a good idea, unless they are improved (Fractal, Inheritus, SSB, RFV2...)
