### ISSUE TITLE
Add Sequential

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Rotations#261]
Sequential was a nice KotH with the idea of encourage players to attack and move forward to capture all the hills, unlike most of the other maps having a point system.  I think that instant ignite should be turned off before and that players are not pushed by their team's TNT before being added to the rotations.

**Comment by Timothee38** [comment]
@Electroid Now it looks good, I agree with it's addition!

**Comment by CoWinkKeyDinkInc** [comment]
The classes made it work much better.  :+1:

**Comment by Electroid** [comment]
Nah.
