### ISSUE TITLE
Remove Nivalis from rotations

### ISSUE THREAD

**Issue by cgode69** [OvercastNetwork/Rotations#265]
This map literally clogs the destroy rotations. I played this map many times and that was too long : the frontline didn't move, the monument is defended. When you try to rush the monument and kill a defender, he just needs to go out and can easily kill us. 

I checked the matches on the last 24h, 4 games out of 12 games lastee in more than 40 minuts

**Comment by thestrangeboy1** [comment]
Removed from the merge of Destroy and Alpha.
