### ISSUE TITLE
Add DK Crossovers DTE into Primed Rotations

### ISSUE THREAD

**Issue by Arzanex** [OvercastNetwork/Rotations#266]
Its quite an enjoyable map, I don't see why this can't be added. Gameplay is quick and fun, much like the older version of DATAstation. 

Opinions?

**Comment by ParaSpider** [comment]
Can the new version be tested so we can make evaluations on whether it could be rotation worthy or not?

**Comment by AnthonyTag** [comment]
Primed doesn't exist anymore...
