### ISSUE TITLE
Add Hanger to Rotations

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Rotations#274]
Hanger is a neat mini TDM with scoreboxes and it used to be on rotations 6+months ago for a little bit. Honestly I don't see why it was removed. The map IMO was enjoyable. Tha ratings IMO also aren't that bad as of August when the rating was a bit over 3.6

**Comment by Shaymin492** [comment]
With the changes suggested above it is a +1 from me.

**Comment by Electroid** [comment]
Looks like this isn't going to happen.
