### ISSUE TITLE
Remove Sandstone Temples

### ISSUE THREAD

**Issue by Shadowbladz** [OvercastNetwork/Rotations#307]
The map is so cluttered and the way it's built encourages hiding due to the amount of places that are hard to see and look through.

The huge amount of cover also pretty much makes bows useless unless you're within 10 blocks.

**Comment by thestrangeboy1** [comment]
Pretty good rating at 3.76 currently. I don't think too much cover on a map is a bad thing. Yes, it does make bows not as useful, but who said Rage has to be open and easy to get bow kills? I wouldn't say hiding is the easiest thing to do as most structures aren't too big to the point there's a lot of space to not be noticed. I think with the terrain, if you have a height advantage over a player, bows would be more useful there which I think the map does well at.
