### ISSUE TITLE
Add Thunder to rotations

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Rotations#318]
Hey, I'm exited to see if my map Thunder has a chance to went to the rotations. There are a lot of ratings, most of them are quite high. As far as I know from Tywnis the average is 3.7. Players really enjoyed the map. I was updating the map a few times to fix problems at the spawns and at the wool room. Furthermore, Electroid finally updated the XML, to add a no void filter.

Thread: https://oc.tc/forums/topics/53eccdfbc296350c32001fff

I hope you like. Maybe ratings changed ;)

**Comment by yoyopower** [comment]
Ratings are not good enough at the moment. Improve the map and then you can reopen this issue.
