### ISSUE TITLE
December Rotations/Servers Redux

### ISSUE THREAD

**Issue by mrapple** [OvercastNetwork/Rotations#325]
- [ ] Merge Control maps into Deathmatch
- [ ] Merge Destroy into Alpha and Beta
- [ ] Remove Capture2
- [ ] Increase server dynamics
- [ ] Keep Deathmatch online
- [ ] Trim Alpha, Beta, Deathmatch maps based on ratings
- [ ] Trim other rotations based on ratings

**Comment by SheriffSoco** [comment]
So is any of this happening?

**Comment by Electroid** [comment]
Yes, it's being worked on. No doubt later than it should have, but it's reaching completion.

**Comment by mrapple** [comment]
https://oc.tc/forums/topics/54bf3fff5f35b9a377001812#e2

**Comment by SheriffSoco** [comment]
Alright, thank you

**Comment by Z3R0Z3R0Z3R0** [comment]
One idea for this big change is #375 , by adding a new server for newer maps we make a lot of people happy.

**Comment by CoWinkKeyDinkInc** [comment]
Looks like everything here has been accomplished.
