### ISSUE TITLE
Put "Scorched Grove" back into Regular Rotations.  

### ISSUE THREAD

**Issue by Statcoman** [OvercastNetwork/Rotations#326]
It would be really nice to have the map "Scorched Grove" back into the OCN rotations.  This map provides say a chance for more teamwork and entertainment for everyone.  This map also rarely gets rushed and would provide defenders to have a more enjoyable time on OCN instead of having every single map for hours getting rushed.  

Thank you for your time.

**Comment by koipen** [comment]
@Arzanex Can you elaborate?

IMO, it shouldn't be brought into rotations until we get a comprehensive dynamic rotation overhaul. The map is 75 vs. 75, and currently - at best - it's played at around half of that. It really doesn't function as it's intended.

That being said - if Eclipsen agrees to it - it's all up yours.

**Comment by Arzanex** [comment]
@koipen The fire swords and bows inside the statues are quite overpowered. I remember more hidden items like these but I forgot where they were.

**Comment by Oo-TheFrog** [comment]
Can this be added to destroy now that its back? Its a very fun map many people defend on it.

**Comment by yoyopower** [comment]
Too big at the moment, could be considered in the future.
