### ISSUE TITLE
Remove Tebulas

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#333]
The gameplay of this map happens almost all the time around spawn, theres waaay too much spawnkilling since its the main thing people do. Its just going outside spawn and getting shot or  killed by someone that its been jumping for a long time around the jump pads. Its really difficult to kill someone when he is 3-5 blocks on top of you, and this is abused very often. Also, if you manage to kill the spawnkillers, there will be another 1 or two guys hiding behind the walls swinging their swords at everyone that walks away from spawn. The way it plays looks like its designed for spawnkilling, and people just use the middle as a way to get to the other teams spawn.
Also, not sure if this is a problem of the map, but i have seen a lot more people glitched in the floor than on other maps (like the flying people bug, but the only thing you see is the name) so this makes it even more difficult to take the spawnkillers out

**Comment by thestrangeboy1** [comment]
I agree with it's removal, the majority of kills are from the opposing team attacking the path in front of spawn and I've also never really seen a point of using the bottom area of the map.

**Comment by Ipskie** [comment]
+1 spawn killing a pretty major part of the map, with the lower areas not used much (the upper areas too, to an extent)

**Comment by thestrangeboy1** [comment]
Removed.
