### ISSUE TITLE
Remove SamplesDTM

### ISSUE THREAD

**Issue by TNTTurtles** [OvercastNetwork/Rotations#339]
Yeah, the map is pretty damn bad.
Horrible monument placement leaves to this map being nothing but stalemate, which makes gameplay terrible and tedious.

**Comment by itsmartin** [comment]
https://oc.tc/maps/samplesdtm Ratings are pretty low, 2.94.

**Comment by matic0basle** [comment]
@itsmartin Looks like they improved a bit because yesterday they were 2.88

![]https://camo.githubusercontent.com/1e97f46f4521779354073e4383b3dba492ad0d57/687474703a2f2f692e696d6775722e636f6d2f756f6a6d7449542e706e673f31

**Comment by matic0basle** [comment]
This can now be closed since the map has been removed (Thanks Cubist)
