### ISSUE TITLE
Remove  Banana Split unless improved.

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#344]
This match its one of those maps that almost always get rushed, since the void gap its reaaaallly small, and the trees give too much cover. You cant shoot everyone, because in a couple of seconds they are already at your base. Since theres no pick on spawnkit, the lanes that go to the wool are really weird, and the woolroom is too open, it doesnt attract people to defend, and it usually ends in some guy blockspamming all the way to the wool or skybridging from the last tree. Trees are a big problem at this, since they block your vision to see the enemy and give really easy spots to bridge from and to other sides. Theres really no place to do stuff, the map its just a way to the frontlines, everyone its either there shooting some people or painlooping, blockspamming hoping to get into the wool.
My suggestion to improve its to make the void bigger, make height limit lower, remove some trees, add chests with defense supplies, and change the woolrooms to make them less open,  so it encourages defense and make it less easier to rush into the wool.

**Comment by Tapetepato** [comment]
Something else i have noticed, is that this is one of those maps that gets annoying to be on after the 1rst minute of the game because of all the blockspam (i mentioned in that people blockspam and painloop this map all the time.
These are some screenshots from a 4:00 minutes match:
![2015-04-25_13 08 59](https://cloud.githubusercontent.com/assets/8422075/7334072/bac837a4-eb4c-11e4-8c43-5e6dd14992be.png)
![2015-04-25_13 09 04](https://cloud.githubusercontent.com/assets/8422075/7334073/bac9f918-eb4c-11e4-9ed7-8213d6a4ae72.png)
![2015-04-25_13 09 08](https://cloud.githubusercontent.com/assets/8422075/7334074/bacb5ce0-eb4c-11e4-9386-326fb37f29f6.png)
![2015-04-25_13 09 22](https://cloud.githubusercontent.com/assets/8422075/7334075/bacfb45c-eb4c-11e4-92f3-7eb219684d3f.png)
![2015-04-25_13 09 18](https://cloud.githubusercontent.com/assets/8422075/7334076/bad6703a-eb4c-11e4-94a9-4f2ed52f95d6.png)

**Comment by Tapetepato** [comment]
Not sure if this old issues are still being considered, but anyways, im going to say more about the map, something that happened in the last matches i played here.
As seen in the above comments, and in the OP, people painloop a lot on this map, causing a massive ammount of blockspam. When painlooping, people usually get in the woolroom.
I gave a little opinion on why the map was broken and someone told me it's fun to defend because you get the challenge of killing to make a pickaxe. The thing is, by the time you killed 2 of them, there's still people going across, blockspamming, running, skybridging, etc, everytime they die they do it again. Since there are no supplies chests and wood is too easy to destroy with the axe, a wood defense is completly useless. You have to kill people, craft an axe, pickaxe, shovel, and more shears to destroy the islands and make a sandstone wall and destroy trees (oops, i have to go, will continue writing when i come back home D:)

**Comment by Tapetepato** [comment]
Not sure if this old issues are still being considered, but anyways, im going to say more about the map, something that happened in the last matches i played here.
As seen in the above comments, and in the OP, people painloop a lot on this map, causing a massive ammount of blockspam. When painlooping, people usually get in the woolroom.
Since i feel like there's more to extend/say i will just make another opinion about this map:
1) The void.
The void gap is pretty small, and there are 2 islands on the sides, wich makes it even easier to bridge across from side to side. When people get to the frontlines, there will be at least 3 bridges on less than 5 seconds. People can bridge from the sides to the islands, from the middle, and to the trees (we will get to them later). I feel like to fix this map you should go back to when there were no islands, and maybe make the void gap bigger.
2) The spawnkit.
I don't think there's that much problem with it, whoever, in my opinion the knockback stick should be on the hotbar instead of inside at the top of the inventory, since a lot of people wont probably see it. Also, the arrows. It's really rare to run out of them since matches are ridiculously quick, but i have ran out of them some times, and the killreward is really low (i don't really remember what it was, 5 arrows per 3 kills or something like that?). Also, getting iron for pickaxe, shovel, armor, sword and a lot of shears isn't easy, especially with all the rushers, so, i think you should add 1 or 2 more shears, or make it so the durability doesn't make them break. Maybe add a pickaxe too, even if it's a golden or stone one, it would help a lot. There's also too many blocks for blockspamming, but they are not enough for defending. Maybe add a defenders chest, or maybe since this map desesperately need to be changed; a class system with a defender class.
3) The iron.
There was a thread about broken maps on the forums recently, and i mentioned that one of the problems with banana split was that you didn't have a pickaxe, and someone said that defending is fun because you need to kill for one iron pick. While this may seem like a good thing, it isn't. It slows people down, and defending shouldn't be a thing you should wait for or kill for, considering how easy it's to rush and how difficult it already is to defend. The woolroom iron may seem like a little thing considering how people can get it by killing or by finding it from the floor, but since (again) the map gets rushed a lot, people get it before the other team has enough time to craft their whole items and armor, making it really difficult to stop them.
4) The trees.
Too much of them. Too high. They make it extremly easy to get in and out of the woolroom, and this is one of the main reasons the map gets rushed. Shears eventually break (see my points on "spawnkit") , and you can't be on the wool defense, killing people for iron and destroying trees at the same time. I mentioned in the point about the void that there were too many bridges in a fast time, and a lot of times, 2 of them are from the trees. There's the vines everywhere and first thing a lot of people do is climb up the tree at the frontlines, and go by there. It's really difficult to get detected on the trees, since they are too close together and too high, you will most likely go to the last tree without getting noticed. From here, people can bridge straight up to the woolroom, or drop into a vine/cobweb. For defenders, it's a real pain to get rid of them since shears break, and it's really slow to break the wood. People can also hide, and even blockspam around them, making the top of the map a big wool, wood and leaves mess. You should lower them drastically and remove some of them, maybe the smaller ones and the ones that come out of the big ones. This would still generate an skybridge problem but would be easy to take down.
5) The map itself:
The middle is too big and there's nothing to do there. It's just a place to blockspam, used by painloopers a lot, and sometimes even teamgriefers that want to get to the flame bow first at the start, or just get fast to frontlines. The wools are at the back. No one ever looks there unless they really want to defend, wich is sadly a weird thing to see nowadays. People don't see them, and
if they see, they see something weird, a woolroom that doesn't look like a wool room and a path to the wool that doesn't seem like a normal path to the wool.
First off, its all made by clay, sandstone, wool and grass, stuff that is difficult and slow to destroy if you don't have the right tools. They are too small and different, making it difficult to defend. There is also the slabs and fences thing, that makes people able to get from one woolroom to the other in seconds. They make a 3 blocks bridge, jump and run, there's even a woolroom entrance from the side!. You should block up the woolroom, you can enter from literally everywhere, jumping from the top, running from the side as i mentioned, from the front, from behind, etc. It would work better if the woolroom was a normal one, a bedrock cage with 2 lines of cobwebs, just with an entrance on the front. Now, here's the thing i can't see how to improve and maybe this is one of the reasons the map should be removed or remade completly. The woolrooms. How do we make people notice them? a lot of maps have the wool like that, on the back, and no one even bothers to look at it. The only solutions i have come up with are;
1. Add signs saying "wool room is that way --->" "defend that"
2. Remake the map completly so wools are infront or at the sides of spawn.

So, this is basically what i think should be done.
Lower trees and remove some a lot of them.
Add a chest for defenders or even a defender class (and an attacker one perhaps? with just 16/32 blocks)
Move the knockback stick to the hotbar instead of inside the inventory.
Change the woolrooms and the path to the wool to regular ones.
Add extra shears (on the spawnkit or in the defender chests).
Remove side islands and/or make void gap bigger.
Add signs to show where the wool is or remake the map completly.

**Comment by yoyopower** [comment]
I've replaced the map with Banana Split II due to the large improvement in ratings. If there is no noticeable improvement in gameplay it will be removed entirely.
