### ISSUE TITLE
Remove Kï from Primed Rotations

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Rotations#345]
There are way too many things wrong with this map to keep it in the rotations. 

First, there is a void gap which prevents people from bridging. This is not a problem at it's own, however, people build icari all the time, making it still easy to cross that gap and making that void gap region useless.

Second, the icari-bridge makes this map a TNT-run feast. The map is made in such a straight cuboid way you can easily block spam over it with TNT, annihilating most of the enemy monument in seconds. Even without icarus the map plays bad. Everyone builds spreads and start killfarming each other and the opposite monument. This doesn't motivate team play, or variety.

Third, the map isn't really special in aesthetics. We already have enough stained clay and quartz maps, do we really need one more? Especially one that is (covered in first and second point) rushed, where regions that should take away an aspect of TNT maps have no effect, and where no team play is encouraged.

I don't think this map should be improved, just instantly removed. I think that because the previous changes (from open TNT rush map to a map in a box with bad gameplay and lack of teamwork) were not really effective.

**Comment by HardstyleRaver2** [comment]
I agree with its removal for similar reasons above.

**Comment by statcoman** [comment]
Yes please, The map and gameplay is just plain awful.

**Comment by Arzanex** [comment]
I personally enjoy the map, but I don't have a particular reason why.

**Comment by Shaymin492** [comment]
+1, this map is nothing more than icarus painlooping.

**Comment by ItsMiiOlly** [comment]
Removed.
