### ISSUE TITLE
Remove Dust.

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#350]
Just like the others ragetdms, they have too much spawnkill when it plays. Most of the time you will get spawnkilled, because people usually stay hid somewhere and shoot you from a lot of places, this are the most used ones.
![dust](https://cloud.githubusercontent.com/assets/8422075/5597031/04b14e72-9261-11e4-83b7-40b21c426f60.png)
Almost all of them are outside spawn, because, once you kill them, you keep going until you get on their spawn exit and start shooting. Yes, sometimes spawnresistance will save you for some seconds, but you will get shot before the blindness goes out.
These are small places where everyone is coming out of spawn, and most of the time someone will hit you or shot you because you walk 5 blocks outside.The instant fuse tnt is kind of frustrating sometimes, since you can kill someoene and at the same time his tnt blew up and even if you run away 3-4 blocks, it still gets you, and it helps too to spawnkill, on the place outside red spawn you can carpetbomb them when theyre walking outside, or on the tunnel outside blue spawn, where most of the spawnkill happens because its a 2x3 blocks tunnel.
Also, i noticed that the map is very unbalanced and different from both sides, its just too different, asymmetrical.
This map is full of small tight crowded places where you can hide,  bowspam or place tnt and hope to get high numbers of kills.

**Comment by matic0basle** [comment]
I disagree. The map works really nicely IMO and its quite balanced. Some matches I play are easy wins for blue some for red. The teams are quite equal.

As for the small places to be at and farm kills eventualy you will get killed. Either you miss or someone comes behind you, you won't stay there for long. Even smart TNT placement is a guaranteed death in some of those spots when the person hiding wont even see the player.

The map is fine. Its a nice map with decent gameplay and looks nice. Its really fast paced which is great because you dont have to look for the enemies to get a couple kills.

So :-1:

**Comment by mrapple** [comment]
Remove *the highest rated map*? No.

**Comment by Tapetepato** [comment]
Yeah i tought it would be high rated since its base on a map of CoD i think and because everyone loves spawnkillfarming

**Comment by firstvirus92** [comment]
@mrapple *[Overrating](https://github.com/OvercastNetwork/Rotations/issues/319#issuecomment-68180705)* the rating system? Yes.

**Comment by mrapple** [comment]
"Furthermore ratings aren't really dynamic and cannot distinguish between map updates unlike real players." You're wrong. Ratings are for the most recent version of the map.

**Comment by mrapple** [comment]
We watch the change in ratings for maps as updates happen, to know if it was good or not. We're working on more analytics, but for now, ratings are a good indicator if people like a map.

**Comment by ItsMiiOlly** [comment]
@Tapetepato It's high rated because it's quick and fun. You get into the "action" quick; it's fast paced; the TNT adds an element of gameplay etc. I've played Dust a lot, and I have seen no spawn killing.

Every map has its flaws. We might as well remove every map from rotation at this rate.
