### ISSUE TITLE
New Blitz Rotation

### ISSUE THREAD

**Issue by ItsMiiOlly** [OvercastNetwork/Rotations#351]
So using the in-game ratings and the feedback from the forms I put out, I've created a new Blitz rotation. I got a lot of feedback from people saying that they wanted the new rotation to be based off the [old one][1] so I tried to go for that. The rotation is as follows:

 - Metallicus
 - Deadwater: Pirate's Isle
 - Battle of Lyndanisse Blitz
 - Bliss
 - Drow's Crevice: Blitz
 - Blitzkrieg
 - Harb Blitz
 - Abandoned Zoo Blitz
 - Wind Waker
 - The Complex
 - The Arena Blitz
 - Arbaro Blitz
 - No Return
 - Cairo Blitz
 - CotBot

Thanks to Matsuzen for helping me out! Feedback is much appreciated.

[1]: https://github.com/OvercastNetwork/Rotations/blob/64d379802578be3b4f2df0abc6f92ce8fdb6f8ce/EU/Chaos

**Comment by Timothee38** [comment]
Sounds good in my opinion, these maps are all nice to play!

**Comment by matic0basle** [comment]
All looks good to me. Good amount of maps, maybe could use a bit more but seems good. Nice to see updates even with the small amount of people that play it.

**Comment by ItsMiiOlly** [comment]
@matic0basle I tried to include some more but there's quite a big lack of Blitz maps now-a-days. :S

**Comment by DoomRobotBoy** [comment]
Looks good.

**Comment by rockymine** [comment]
@ItsMiiOlly: I like it. You said there is a lack of blitz maps, what would you like to see? I'm a bit uninspired right now. Maybe I could do something from your ideas.

**Comment by ItsMiiOlly** [comment]
@rockymine From what I gathered from the feedback forms, it seemed people wanted to see some maps that have an element of "skill" and "challenge" to it. For example in Metallicus, you have to be careful when you're fighting because it's a UHC. That is what makes it fun to play on. 

Something Matsuzen brought up was that the old rotation had maps that made it feasible to win a "clutch" (win a 1 v 4 for example). Maps like Aerugo weren't good for that since it was too small.

Anything that includes some of these elements would make for a good Blitz map.

**Comment by CoWinkKeyDinkInc** [comment]
Looks great :+1:

**Comment by HardstyleRaver2** [comment]
It looks good.

Anyways, what is the rating for Drow's Crevice?

**Comment by ItsMiiOlly** [comment]
@HardstyleRaver2 3.57 from the form, 3.37 from in-game ratings.

**Comment by Cevans98** [comment]
Can we add Industrial Citadel? It's a tonne of fun to play and like "No Return" is one of those really different, interesting maps that requires more strategy.

**Comment by HIVERaven** [comment]
@Cevans98 Industrial Citadel might be the lowest rated map in the history of map ratings. It takes waaaaaay too long to complete.

**Comment by matic0basle** [comment]
@HIVERaven Probably not the lowest. Might still actually be above 3.

**Comment by ItsMiiOlly** [comment]
It has a rating of 3.33.

**Comment by Cevans98** [comment]
A number of things to make it quicker:

 - Max time limit (8 mins or something?)

 - More damage done with the weapons (increase dmg/reduce armor points?)

 - Make it so only one side exists, not two.

I'm sure there are others, but honestly that map is one of those, previously mentioned, that provides a different gameplay than the rest of the rot and could make it more interesting

**Comment by yoyopower** [comment]
Secluded Lakes has been in the repository for a fairly long time, and it hasn't seen much testing. While there's only been 10 ratings on it so far, the average is 4.3. I'll push out an update to fix some of the issues that were raised, but it could be considered for the rotation.
