### ISSUE TITLE
Add Greecia II

### ISSUE THREAD

**Issue by CatchingMC** [OvercastNetwork/Rotations#353]
My map, Greecia II was tested today, thanks to chickolympics. I would like to know if it may be add to the rots soon.

**Comment by matic0basle** [comment]
It was added to the repo about 4 hours ago. I think before the rotations it should get some setnexting to get ratings.

Also the repository is not for feedback. Post a feedback thread on the forums for that.

**Comment by ParaSpider** [comment]
I feel like the map could be less lengthy to get to the wool, and maybe take down the cliff 4-5 blocks.

**Comment by DoomRobotBoy** [comment]
I think it's not ready yet. 

1) The map is way too small, even for a 16v16. I'm surprised I was actually able to leak the core, with everyone being so close on one another. 
2) It contains loot that doesn't work well. Iron blocks make a gear difference too large (I thought there was limited iron). TNT it way too OP for such a small map.
3) Everything is so limited. Limited arrows, limited blocks. I can understand you're trying to encourage teamwork, but cutting immensely down on blocks and arrows won't do the trick.

I suggest you take this map and make it larger. Not in like a 50v50, but more of a 20v20 that actually fits the size of the map. Remove the TNT. Iron could be kept if the supplies are enlarged (they can be renewable or just have a large iron mine). Add more supplies. Add more arrows, 16 is way too few. There are also none on killreward. Either add a killreward giving 8 arrows per kill or just boost the arrow amount up to 48-64.

After you've done similar changes, and have it setnexted a numerous amount of times, then it can be questioned for addition to the rots.

**Comment by thestrangeboy1** [comment]
Map is wayyyy to small and reasons listed above is why I'll close this.
