### ISSUE TITLE
Remove Interitus TE

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#356]
When it plays its too chaotic, people often painloop and there's barely any cannon unless maybe one spread on top of the diamonds zone to killlfarm. People often just bridge to the sides as soon as they get out of spawn and rush it over and over again. The core is also never defended, and the monuments are really easy to get since you can sneak inside one and fill it with tnt. Also, if it lasts more than 5 minutes, its difficult to get diamonds and other stuff so there's even more painlooping and bridging on the sides of the map. The map rating of the newest version is 3.53 and on all versions 3.50. I feel like this is a really painloopy map.

**Comment by HIVERaven** [comment]
3.5 isn't a bad rating, it's a good map for multiple kinds of cannons. I see a lot of icaruses and a good amiunt of whiskey types used on the top deck. It is interesting to defend. 

I'd like to know how it and the rest of the primed maps rated on the forum survey before they any get removed.

**Comment by CoWinkKeyDinkInc** [comment]
I think bumping up the player limit a bit might make it play better.

**Comment by thestrangeboy1** [comment]
Removed.

**Comment by Tapetepato** [comment]
@thestrangeboy1 could you open it again now that it's on Ranked? its the TE one but its basically the same, if not worse because there are less players and it gets even more rushed and less defended

**Comment by thestrangeboy1** [comment]
Removed.
