### ISSUE TITLE
New Rage Rotation

### ISSUE THREAD

**Issue by ItsMiiOlly** [OvercastNetwork/Rotations#358]
Following feedback from in-game ratings + the feedback forms, I've created a new Rage rotation. The rotation is as follows:

 - BipBetaMC
 - Foxtrot
 - Bliss: Rage
 - Into The Jungle
 - Dry Wound
 - 101 Rooms
 - Gravestone
 - Rage Quit
 - Deschutes
 - Sandstone Temples
 - Proelium
 - Secluded Palace
 - The Dome
 - Fallen Courtyard
 - The 6th Law
 - Plus Side
 - Arid Crossroads
 - Dead Town
 - Grimsnes
 - Swarthmoor

Feedback is much appreciated!

**Comment by matic0basle** [comment]
I'm not that sure about The 4th Law and Dead Town but everything else seems fine with me.

**Comment by TheGunningAlien** [comment]
This would be good but I would like to see Oculo re-added! A lot of the rage community like this map and would like it to be re-added.

**Comment by Avaleer** [comment]
I personally am not a big fan of Grimsnes but the list seems good :)

**Comment by ItsMiiOlly** [comment]
@matic0basle The 6th Law has a rating of 3.59 from in-game and 3.79 from the feedback forms. Dead Town is quite a new map but I'll give it a chance since it's been well-received in-game. 

@TheGunningAlien I was not sure what to do with this map. It's been requested quite a bit from the feedback form but if we take a look at it from a gameplay point of view, it honestly isn't that good. Dodging arrows is near-impossible and the thin alley ways make it so you don't need that much skill just to kill someone.

@Avaleer I've removed the weather from the map so hopefully it will play better than it used to. :)

**Comment by matic0basle** [comment]
@ItsMiiOlly On Oculo you can dodge arrows quite easily. Using the cover to your advantage should be something that players should learn to do not just run straight down the middle. And you need quite some skill on it. You need to evade the arrows being shot at you. You need to get into a possition where you can shoot the enemies without them being able do the same to you and when it comes to swords you need to use cover with your strafind to beat the enemy. 

The only issue I see with it is that you can jump on the walls with the glass panes. If those were full blocks it might be better but then again, might not since the panes offer an advantage which can be used as a tactic.

I think Oculo should be added.

**Comment by TheGunningAlien** [comment]
@ItsMiiOlly you can avoid arrows pretty easily but it would be better if the ceiling was one block higher.

**Comment by HIVERaven** [comment]
@matic0basle Oculo held up the rest of the rot, was easily glitched on to escape, was extremely chaotic in the jump pads, and suffered from spawnkill issues. It should not be re added

**Comment by SheriffSoco** [comment]
@matic0basle Oculo should definitely not be readded. It has overall messy gameplay.

@ItsMiiOlly I like this rot. My only change would be a rot without Sandstone Temples

**Comment by CoWinkKeyDinkInc** [comment]
@TheGunningAlien I was thinking of doing that, but that would make it more easier to shoot at players.  The map is good, I think that it should be one or two blocks wider and that's all. 
My only problem is that the mods removed it, despite them knowing it had high ratings (at the time? currently 3.55) in #78.  Then later, they defend why their maps should be kept with a rating.

**Comment by MrBloxley** [comment]
Sounds good :+1:

**Comment by Avaleer** [comment]
kool :)

**Comment by BeanButt** [comment]
Why 101 rooms? It's hard to strafe and people mostly stand in the corner with their bow drawn waiting for the player to walk around the corner to shoot them.

**Comment by SheriffSoco** [comment]
@BeanButt because it's fun to play, even with the lack of skill

**Comment by EyQu** [comment]
:+1:
