### ISSUE TITLE
Remove Infernal Shadow

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#360]
This map a lot of times get rushed, and yes, some times people defend but its really hard. Skybridge is an issue since you spawn with too many blocks and if you kill some guys running on your base you will quickly get your inventory full of good and netherbricks. The lanes most of the times are full of blockspam since theres not really something that stops them except from that little bedrock wall that is outside spawn. 
This is just some random match i jumped on, but all the games on this map usually get like this in 2 minutes.
![2015-01-10_12 03 16](https://cloud.githubusercontent.com/assets/8422075/5692578/ec52799e-98c0-11e4-8dfa-ae44e3d98625.png)
![2015-01-10_12 03 09](https://cloud.githubusercontent.com/assets/8422075/5692579/f02a7472-98c0-11e4-9380-6f4d74e1a922.png)
Voidgap is small (20 blocks) and this makes bridging to the other side really easy on the first minutes of the match. 
Theres also de "tunnel" that is around the lanes that, most of the time, when some rushing guy fails his blockglitch, he falls on that place and then pillar up:
![2015-01-10_12 03 01](https://cloud.githubusercontent.com/assets/8422075/5692586/3097177c-98c1-11e4-962e-f16b9b3d8415.png)
The main reason i see this map can last long enough even with guys constantly blockspamming and painlooping into the wool, is the location of spawn. If theres a guy rushing, or some guy kills you as a defender, you can run out of spawn and kil him just a couple of blocks from where he was when you saw him. Almost every game is like this, a ton of blockspam with both people defending and people attacking painlooping everytime they die to get back on the wool.
It also has a rating of 3.40 and according to mapdevs, anything below 3.50 is below average.

**Comment by Tapetepato** [comment]
Toughts?

**Comment by Ipskie** [comment]
From the main page: Do not: "Bump issues to receive a response (all issues are acknowledged)"

**Comment by thestrangeboy1** [comment]
Removed.
