### ISSUE TITLE
Add Astro to Primed

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Rotations#361]
I really like Astro.  I enjoy that it has long matches and also has a good rating of 3.64.  The only problem is that it is almost only seen on Alpha, barely anyone crafts armour and that team griefing with TNT is extreme.  It is common to find three or more griefers on this map, and I think the solution for now would be to moving it to primed until TNT licensing works on all servers.  Then we could move it back to Alpha, or add it to Alpha and Primed.

**Comment by HIVERaven** [comment]
This was originally on primed, and player horribly due to the size.

**Comment by CoWinkKeyDinkInc** [comment]
I've checked the file history, it was only on rotations for about the first 14 hours of Primed being released.  I think it might do better now since everybody tried out Primed by now.

**Comment by DoomRobotBoy** [comment]
I think the map is also a bit oversized for Primed. Not to mention that when the amount of TNT like it is on Primed this map could also generate a lot of lag.

I suggest taking the theme/layout and make a Primed-friendly version:

- size of map reduced.
- TNT spread out over map, with some chests around the frontlines.
- improvement of center island (with the amount of TNT Primed offers the center island will be rip before someone can even get there. If the center is revamped, With for example diamonds in the center, iron surrounding that, both also on surface. Some buildings with TNT ion the center. Possibly pre-built bridges).
- more bedrock walls in the spawn islands; to disallow OP defenses.

**Comment by CoWinkKeyDinkInc** [comment]
I think the size is fine, I think that there should just be smoother cliff to one end or something that makes players go down easier, as some would only go down if they water jump or wait until somebody else places water that flows down.

**Comment by CoWinkKeyDinkInc** [comment]
Now that TNT Licensing is global and on all servers, would adding this to Primed still be a good idea?

**Comment by Z3R0Z3R0Z3R0** [comment]
@CoWinkKeyDinkInc It doesn't seem to really have gameplay that involves the TNT too much. It's too big, and the cores are so far into enemy territory and so high up that they can't really be cannoned at easily. Theres also really no supplies to cannon at, and I don't think it would play very well on primed.

**Comment by Electroid** [comment]
The map is really large for the average player count on Primed.

**Comment by thestrangeboy1** [comment]
I agree with @Z3R0Z3R0Z3R0, there's simply nothing to cannon like at all. TNT is really only used for a defense and maybe just to get rid of skybridges? Middle islands tend to go badly as well for most maps which makes it hard for the opposing team to gain control of, especially when the team that has control keeps coming back first to get diamonds instead of the iron in their ship. The endstone in the terrain makes it hard to actually have damage dealt to the other team's side too.
