### ISSUE TITLE
Remove Golden Drought II

### ISSUE THREAD

**Issue by FlavorfulGecko5** [OvercastNetwork/Rotations#362]
http://i.imgur.com/4taMPm0.jpg

This is how many people play the map at ~1 EST, when there are approximately 800 people on the network. It eventually got up to a 25v25, but of course by then the map had been rushed and the game ended in 5 minutes.

The ratings (which some people think mean everything) are only slightly above average. However, I'm sure the majority of people who rated it 5/5 are objective farmers that abused the map to boost their stats.

The map is:
> Too easy to rush because the lanes are so wide and map is so big.
> Too easy to farm objectives on because the lanes are so wide and map is so big.
> Nearly impossible to defend on because the lanes are so wide, the map is so big, and you can go between wool rooms simply by bridging over a gap.
> Too big for our network's current player count. (Max. 1000 almost all the times. This also partially accounts for the above three issues.)

This map, in reality, is Ozone sized. It really should be a 75v75, not just a 40v40. We simply can't have 75v75 maps in rotations because the network is dying.

**Comment by mrapple** [comment]
> However, I'm sure the majority of people who rated it 5/5 are objective farmers that abused the map to boost their stats.

No, you can't say that.

**Comment by DoomRobotBoy** [comment]
I agree. You can only defend with a squadron of friends, an occasion that happens so often, you can't really keep a map in the rotations for. The map size and team sizes I feel are fine, but because defending is not encouraged (even though it's very possible) I think the map should be improved or removed.

**Comment by Mikeg542** [comment]
I don't know why it would be added back. I don't really know why it is getting rated ok, but it really doesn't have any redeeming features gameplay wise.

**Comment by Tapetepato** [comment]
+1

**Comment by firstvirus92** [comment]
>Too big for our network's current player count. (Max. 1000 almost all the times. This also partially accounts for the above three issues.)

That's a problem of the network, not the server. However the inability of the staff team to properly fix this server system might justify this, have a look at the Moonlight Summit issues.

>This map, in reality, is Ozone sized. It really should be a 75v75, not just a 40v40. We simply can't have 75v75 maps in rotations because the network is dying.

It should be a 50v50, but the staff team was a bit sloppy at restoring initial team sizes. Many other maps are affected as well, go ahead and make an issue on the other repo.

**Comment by FlavorfulGecko5** [comment]
@mrapple  Yet map developers can make assumptions about how people rate maps? (http://i.imgur.com/lSsHJE9.png)

Now, to stay on topic, I'd like a staff member to comment on this with the final verdict. It has become clear time and time again that this map is too large for our player count.

**Comment by mrapple** [comment]
Both you and mike are most likely wrong

**Comment by Mikeg542** [comment]
@mrapple Yeah, going to have to disagree with you there. When a map has been averaging 3.6 for months and months and drops more that 0.5 with a distribution HEAVILY weighted towards 1, then jumps up higher than it was before in a couple weeks, I'm almost certainly right.

@FlavorfulGecko5 See above, this is most definitely an outlier case. New Version based ratings should be treated a lot more cautiously than those from over many months

**Comment by mrapple** [comment]
@Mikeg542 you didn't include any of that information in your post, also the rushers would be rating it 5. I assume that was a typo though.

**Comment by Mikeg542** [comment]
@mrapple Oh, sorry. We are talking about different things here. With regards to this map I may be completely wrong, and I acknowledge that. I thought you were referring to his claim of "Yet map developers can make assumptions about how people rate maps?" 

My bad!

**Comment by SuicuneScale** [comment]
The map plays poorly. It's incredibly hard to defend (The lanes are way too wide), double capping is way too easy, and even [Reshif himself has stated that the map was designed poorly](https://oc.tc/forums/posts/5297c830af7fb0840a001e92). I can't think of one thing this map does better then others, quite honestly.

**Comment by thestrangeboy1** [comment]
Removed in Alpha's new rotation update.
