### ISSUE TITLE
Remove Retaliation from Primed rotations

### ISSUE THREAD

**Issue by Arzanex** [OvercastNetwork/Rotations#363]
We already have two versions of the map. Retaliation II is by far superior and I wouldn't see a reason to keep the original. Additionally, there really isn't much TNT on the map to qualify it to be on the Primed rotation in the first place. 

Opinions?

**Comment by HIVERaven** [comment]
+1, usually gets rushed too. @ItsMiiOlly @Mikeg542 Do you have the rating from the forum survey?

**Comment by Tapetepato** [comment]
i would honestly rather have Retaliation I than II on rotations. this one usually have too much spawnkilling because diamonds run out pretty fast.

**Comment by HIVERaven** [comment]
@Tapetepato gear wise, objective wise, supply wise, 2 is far superior to 1. In the words of either Cratain or Shaymin "They made a 2nd one for a reason".

**Comment by Ipskie** [comment]
At the very least revamp the supplies. There's next to no water buckets and no one ever uses the abundant pistons

**Comment by Electroid** [comment]
Not relevant anymore.
