### ISSUE TITLE
Remove RFV2 from Rotations (or maybe replace it...)

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Rotations#364]
I know how good this map is in tourney play, but as we all know that is far away from public. However, tourney play usually suggests the map as a good basic layout. I do think the same. The map has a great layout but it's small lanes don't really allow it being played with large team sizes. It usually results in a skybridge-race, where once your roof is reached by the enemy all their iron guys will start bridging/farming kills/etc. which will result into your loss. I can't really get a decent defense set up without it being overrun by tons of enemies.

So I suggest we keep the 'basic layout' but change it. aka, replace it with a similar map. A layout like Pursuit of Happiness or NextGen's layout could work better, because of the larger front-lines, and the not so immediate incentive for sky bridges, which is opposite to RFV2 (where sky bridges are usually the only outcome) a great improvement. I don't know if there are other maps with a similar layout, but I think that the idea is there, now just the map.

The rating-average is 3.69, which is in fact still enough to keep it in the rots.

**Comment by Tapetepato** [comment]
https://github.com/OvercastNetwork/Rotations/issues/262 huge +1

**Comment by mrapple** [comment]
> Has a rating of 3.70 and is very popular amongst loads of people on the network. This doesn't need to be removed.

**Comment by HIVERaven** [comment]
@mrapple Why do you close these issues before we can even discuss the points that are made?

**Comment by mrapple** [comment]
I didn't lock it, nothing's stopping you from discussing. If you discuss anything valid, someone will reopen it.

**Comment by HIVERaven** [comment]
@mrapple okay, could you please reopen #357 ? There were quite a few solid points made recently that I would like discussed further.

**Comment by mrapple** [comment]
No, last already addressed the issue.

**Comment by HIVERaven** [comment]
@mrapple No, he didn't. He shut down all the given points by responding with 1 statistic. The rest of the post and many posts below bring up issues that go against last's statistic. He did not adress the issue, but shot it down with a hand picked statistic that supports his ideas.

**Comment by DoomRobotBoy** [comment]
@mrapple Look, I know the map is popular (and well-rated). I mean this map was basically the foundation of CTW with lanes as we know it and has been in the rotations forever. But shouldn't we try to fix issues that occur and try to improve or completely exclude them from current maps? RVF2 is pretty small and doesn't offer much variation in gameplay. Isn't it better to prevent it from ever becoming boring, instead of letting it slowly dig it's own grave. I have nothing but my own observations to support this, since for some reason, new players can look past all the block-spam, sole sky-bridges and unable-to-be-setup-defenses and still rate it decent. 

If the removing/improving/replacing ain't possible I do feel like team sizes should be a bit reduced. Isn't 32v32 too large for a map that is not even 50 blocks wide and 300 blocks long?

If nothing is possible or will be done/thought about I will just let this thread be and won't act further.

**Comment by MrTheSharpie** [comment]
I'd replace it for Pursuit of Happiness, because while the layout is similar, you have classes that encourage you to defend, etc.

**Comment by DoomRobotBoy** [comment]
@MrTheSharpie Pursuit of Happiness was in the rotations, but the author wanted it removed. Since the author has all rights over the map it cannot go into the rotations.

**Comment by MrTheSharpie** [comment]
Oh... then NextGen would be the chance. And when you say RFV2 plays well in tournament... Yesterday I played a scrimmage there and 50 minutes were shooting from one skybridge to the other xD

**Comment by CoWinkKeyDinkInc** [comment]
Not many people liked NextGen, I think that it was too confusing for newer players and they will screw up the only two water blocks in the game almost everytime.
