### ISSUE TITLE
Remove A Watery Grave.

### ISSUE THREAD

**Issue by tanpara** [OvercastNetwork/Rotations#366]
The map has lasted far beyond it's age, and the map itself has it's fair amount of flaws. Being the lowest rated map on OCN with a 3.04, I want to address some things;

**1** Yes, it's a nostalgic map, and previous issues were closed due to removing certain maps from nostalgia as it would mean being the start of removing the server itself. Acknowledged. I personally don't enjoy playing it as well as many others, however it's up in the sky for everyone to discuss. I think removing just this one wouldn't harm nostalgia that bad.

**2** I see players complain a lot when it comes on. Normally, I hear players in chat want to skip it and move on to the next map, or go as far as (before the rating match thing was implemented) tell people to rate it low so it'd be removed. Most of the matches I go on it occurred/occurs, seeming more frequent than other nostalgia maps excluding sand wars.

**3** Defense. Defending is an almost impossible task as they can come from the top, bottom, front, back, and sometimes you'll never know. It's hard to dig a pit with the water, sand, gravel, stone, and mix of materials to break it along with the insufficient amount of wood to build defense supplies, so how do you defend? You can only "watch it" but even then it's too simple for someone to pop by. I also rarely see people defending, only rushing over to their side.

Another problem from the defense is the water. If you break the glass, it's very difficult to clean up.

**4** Match times! Rushing is a tactic on the network, however the issue is that matches shouldn't last 40 to 50 seconds. Usually the discourage of defending causes players to just go toward the core and it's broken, that's it. Matches don't tend to last long on this map.

**5** Clutter. The core doesn't have much room in itself and even though it's by spawn, its just not too much room. Being so, even if there IS a long match which happens once in a while, the map will be very wet with a ton of glass broken to flood it, and stone bricks everywhere around the floor so it's somewhat difficult to navigate.

**6** Lag, not sure if I'm the only one, but I do get lag issues playing this map. May be because of the water or light updates or something. Dunno.

**Comment by EyQu** [comment]
https://github.com/OvercastNetwork/Rotations/issues/336

**Comment by ParaSpider** [comment]
Yes, though I feel that this requires attention first. The other one may take a while to go into effect, if at all.

**Comment by CoWinkKeyDinkInc** [comment]
Blockspamming all over spawn makes it dirt easy way to win this map.  I think if your team cannot cover the obsidian defence with blocks and have it back by three blocks this map might play better, along with more better food than mushroom stew and a small amount of TNT for defence purposes.

**Comment by clemensv14** [comment]
its pretty hard and difficult to protect the core, remove it overcast network, what map is not very good

**Comment by ParaSpider** [comment]
The previous issue was closed about removing Nostalgia. My points still stand, even though the rating has slightly gone up.

**Comment by Electroid** [comment]
Nostalgia will get a retrofit. (Internal issue)
