### ISSUE TITLE
Remove Corrupted Kingdoms.

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#367]
I honestly love this map, it looks beautiful, and its gameplay would probably play well too at 70v70, but sadly, this matches dont happen anymore. I know when people make issues like this one, you just say that its not the maps fault to play at 10v10/20/20 when its supposed to be bigger, but honestly, if there's no way to make it a 70v70 again, you should'nt use that excuse and maps like this should be removed from rotations.
It usually lasts around 2-6 minutes, and that's way too  short considering how big this map is. When this map is played, barely no one goes where the Harbor Monument is, except for maybe 1 or 2 players crafting armor to then take a boat to get easily the enemies' one. That part of the map is really big (with the boats, water, etc) and its almost never used, not to mention the Hillside Monument.
That part of the map ignored even more, since its just a little house at the side of the mountain, and people just walk directly to the iron mines to then rush the enemies' monuments. That monument is usually the first to be destroyed since someone can just craft armor really fast, pillar up their mountain, get the monument without being seen, and usually even running behind the bunch of mountains to get the Harbor Monument too.
What most of people do on this map is: run out of spawn (usually blockspam a bit too ;_;) rushing to the iron on the side of the mountain, then the rest who didn't got there in time goes to the main iron mine. Then, they run to the other side, hopping to get the monument when there's no one there (would've said "when there's no defense on the monument, but the only defense that usually is done on this map is covering it on a layer of blocks and then either just stay on top of it or run away to rush). If one team manages to get that monument and kill a couple of guys that are crafting armor, They already control the other team, and can easily go and spawnkill them.
Overall, i think this map is great and has a great potential if the current player base was bigger, but sadly, it isn't, and it isn't really fun to play this map anymore.

**Comment by CoWinkKeyDinkInc** [comment]
#347 Is discussing moving it to similar maps like The Nile and that harbour map.

**Comment by ItsMiiOlly** [comment]
^ use above issue.
