### ISSUE TITLE
Add Fourchette to Capture Rotations.

### ISSUE THREAD

**Issue by Timothee38** [OvercastNetwork/Rotations#369]
Hi,

So I want to discuss about a potential addition of my map, Fourchette, which is a CTW to the Capture rotations. The average ratings for now is around 3.8 (out of 277 votes, indeed not enough yet to get an average, but still, it has been on for a while. https://oc.tc/maps/fourchette

The reason I can see it added is because it (in my opinion) is defendable, and this in a efficient way, at least from what I've seen/experienced.

Several players have told me they enjoyed it, and the ratings are quite good (I think).

So yes. Any remarks?

**Comment by Buo111** [comment]
I would like to see this map on the rots. Great map to defend! :)

**Comment by CaptainElliott** [comment]
I would like to get a few more ratings before, but it defiantly has potential.

**Comment by CaptainElliott** [comment]
After playtesting this I have come to some conclusions. 

The map seems fairly well balanced, however the front lines need some work - the underneath part never gets used and makes it much easier for players to rush as it is often un-maned. 
I propose that you either removed the top part or completely removed the bottom. Personally I think removing the bottom half will keep variation and make it more fun and interesting that a flat front lines.

I also suggest you make a clearer, more visible way up to the very top of the wool rooms. Currently there is only one ladder going up to it at the very back of the room and it is obstructed. I suggest you make some more ways up to it.

**Comment by Timothee38** [comment]
@CaptainElliott  What if, instead of removing the bottom lane, I removed part of it (like cutting it the same way as the top layer? Players would have to bridge to the woolroom kind of. I could also add some sand blocks for rushers, I guess. Would that be a good idea?

**Comment by Arzanex** [comment]
Needs more testing, Ill see if I can SN it a couple of times this weekend :)

**Comment by CaptainElliott** [comment]
A new update was pushed that should improve gamplay

**Comment by thestrangeboy1** [comment]
Ratings have been very high and the way the front lines works out makes it really great. The choke points of the void gap is really good for defenders, however the back lanes don't seem to be used for defending much. This has just recently been added to the capture rotations though. We'll see if it continues to play well.
