### ISSUE TITLE
Remove Inheritance.

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#370]
It plays really bad, there are a lot of places that are unused like a lot of houses, towers, the lake, iron mines, etc. Why are these parts not used at all? Because everyone nowadays know rushing routes on most of Destroy maps. 
The thing is, this one here, is one of the most rushed ones. It's too big and there's no void gap, and iron is right next to spawn, making it easy to rush/farm even when you are full iron. Also since the map is asymmetrical, there's always one team with the easies route, and they rush directly to the core.
Most of its matches end between 3 and 5 minutes, and there's no way to stop the rushers since there are too many.
Seeing defenses here is really rare, since, again, everyone uses the basic route; take iron, rush for a flame bow, jump, and then run for wichever route your side has).
Also, if you manage to get rid of the rushers, defenses are not going to be really good since the height limit is really low and if i remember correctly water can be just like 1 or 2 blocks above the core. 
Also, you spawn next to de iron, that has water next to it, and you spawn with health pot, making it even easier for rushers to stop from getting damage or heal themselves and continue pillaring to the core.
It also has a rating of 3.46, and map devs said that everything below 3.50 is below average.

**Comment by SuicuneScale** [comment]
I think the main problem with it is that you can't see anyone. Maybe take out a few obstructions (Trees, Buildings).

**Comment by thestrangeboy1** [comment]
Removed in the merge of Destroy and Alpha.
