### ISSUE TITLE
Remove Khaba.

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#371]
It has really poor gameplay, and its like 99% based on grenades. You spawn with 5 of them, and if you hit on the right spot, you will kill someone every 1 or 2 grenades. This makes it possible for people to hoard a lot of them, an then spam them at your enemies. There's really no way of defending from grenades, since they make a ridiculously big damage and radius, and it generates a crazy ammount of particles, making it nearly impossible to get away from a guy with 3+ grenades.
When getting spammed on grenades, only thing you can do is double jump out and hope for the best, but you always get catch. Why? Because the double jump is avaliable too soon after you just used it, making people hopping around the map throwing grenades at everyone.
The map also looks pretty plain and repetitive with the same height on the sandstone ground and there's just a ton of houses that looks really similar.
Not to be rude, but in my opinon, its the tdm with the worst gameplay right now.

**Comment by Electroid** [comment]
It's preposterous to remove a map that is the 6th highest rated on the network, a *4.03* average rating. The map is fast paced and fun, and it doesn't matter if it's more grenade based than anything based. What matters is that people enjoy and like this map a lot. I'm sorry that all maps can't please everyone, but we aren't removing this.
