### ISSUE TITLE
Add Baroque Gardens to Destroy

### ISSUE THREAD

**Issue by ViceWatercolour** [OvercastNetwork/Rotations#376]
It's a very enjoyable map and fits in with the other defend heavy maps; when it has been set, it usually results in a challenging, long-lasting match with a lot of teamwork with defenses and a beautiful aesthetic touch.

It seems many players have loved it in the past, so I think it should be put into rotations.

**Comment by SheriffSoco** [comment]
I would love it if this got added

**Comment by yoyopower** [comment]
The map needs a lot of editing for it to be considered for rotations. For starters, the monuments need to be made both harder to break with uneven teams and more obvious. Teams struggle finding the monument regularly.
