### ISSUE TITLE
add Moonlight summit

### ISSUE THREAD

**Issue by clemensv14** [OvercastNetwork/Rotations#378]
overcast network, would you please add Moonlight summit to the destroy rotations because it is a very good game and its fun. working with teammates, working for money and win together, so will you add Moonlight summit. join people and help us.

**Comment by Arzanex** [comment]
This map has been in the rotations before. It was removed because the map was always played with too little players. This map is good for setnext events, but not suitable for rotations in my opinion.

**Comment by Ipskie** [comment]
Was in rotations in the past, performed very poorly on empty rotations. Might work if dynamic servers were tightened up?

Also the gameplay becomes pretty linear after a point (dump spawn nuggets, rush orb, die, dump spawn nuggets...)

**Comment by Tapetepato** [comment]
it was really killfarmy like other gear maps, imo it just works as a /sn from time to time but not as a rotations map

**Comment by Electroid** [comment]
Outdated and not enough people.
