### ISSUE TITLE
Update Isle [DTC]'s XML

### ISSUE THREAD

**Issue by ThetaMC** [OvercastNetwork/Rotations#380]
Some recent tests have shown me Isle's XML needs to be slightly modified and updated,

*Changes*
- Less blocks in spawn inventory
- Removed useless bits of XML that weren't necessary

http://pastebin.com/vcSbMfiH
(Help me indent please, may be errors, but XML was largely untouched, so its probably fine)

**Comment by firstvirus92** [comment]
Wrong repo, post it on OvercastNetwork/Issues.
