### ISSUE TITLE
Remove/Change Valley of The Dead 

### ISSUE THREAD

**Issue by Cevans98** [OvercastNetwork/Rotations#382]
Please, drastic changes necessary. Reduce the point limit and/or make it quicker to capture a point. Especially on EU, in a 6v6 on the map the game last 30mins+ due to how hard it is to capture a point. Also most people focus on PvP and leave the objective anyway

**Comment by matic0basle** [comment]
> in a 6v6 on the map the game last 30mins+

Its not the maps fault that its not being played at the amount that it is made for.

All maps have really different gameplay if they are not played at the player amount that they are ment for. You won't have the same match on the Nile in a 40v40 or a 5v5. 

I don't think it should be removed as its an interesting map and I haven't noticed any gameplay flaws in it. The player amount making the map last a lot longer than it should isn't the maps fault.

**Comment by CoWinkKeyDinkInc** [comment]
#246

**Comment by Cevans98** [comment]
@matic0basle  The gameplay is too slow, at least for EU. Quicken the point capture to more than 1% per second and it'll vastly improve it

**Comment by Ipskie** [comment]
This is a dupe and should be closed

**Comment by matic0basle** [comment]
@Cevans98 Its not that slow from what I played it. If its like that because of the player count, again its not the maps fault.

**Comment by Z3R0Z3R0Z3R0** [comment]
@matic0basle If the player count rarely suits the map, or the map rarely suits the player count it gets, then it really shouldn't be in that rotation, correct?

**Comment by matic0basle** [comment]
@Z3R0Z3R0Z3R0 Its not the maps fault that the players aren't online or are on other servers. If players change servers when the map comes up then its the maps fault but overall if the player count on all maps is something like in the image the map has nothing to do with it, rather the server dynamics and people not playing on the server.

**Comment by Z3R0Z3R0Z3R0** [comment]
@matic0basle The way I see it, if the map never plays at the required capacity for good gameplay, then it shouldn't be in rots because the gameplay isn't good. Maybe it's not the maps fault, but you got to look at the result here. Almost every time thr map comes up in rotations the gameplay sucks due to lack of players, and thus, it shouldn't be in rotations.

**Comment by thestrangeboy1** [comment]
^^^^^^^ #246
