### ISSUE TITLE
Remove Coniferous Forest

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Rotations#384]
While the map is still being worked on (rocky has residency) it should be removed until the issues are resolved.

 - Defending
  - The map does not encourage defending at all. The previous design of the spawn and caves was quite poor with the caves being extremely small and the spawn exit being only a couple blocks wide but there was still a path going to the flag. Now the spawn is in a different area which is good and the caves are bigger but there is no direct tunnel from spawn to the flag, no signs or path in the ground leading players on the way to the flag. Even chat tips would help. 

 - Easy capping
  - With the map not encouraging defending at all its easy to capture the other teams wool. You can easily exit the flag room that will be empty because defending is not encouraged enough from the top, avoiding combat that you would go through when entering through the caves and you can easily exit at the "side" stairs that are in that area. If you exit the stairs area then you just run back to your side and get an easy cap.

 - King Flag
  - The king flag is a good idea but its not really working out for the map. From the last match all players were mostly just going for that flag (with a few exceptions) and trying to get that flag only completely ignoring the other parts of the map. The map could play better without the king flag because the players only go for it ignoring the team flags that are already extremely easy to cap.

I would provide more information about the player flow but I wasn't able to get enough information because the match I was in ended quite quickly so I will be adding that soon.

I also told rockymine what could be improved with the map and even after giving him tips that he wanted and he replied with "Its just YOUR opinion" and "give me real tips".

**Comment by Electroid** [comment]
Then map didn't make it out of residency, it's removed
