### ISSUE TITLE
Improving Nostalgia & Its Rotation

### ISSUE THREAD

**Issue by Liggy1000** [OvercastNetwork/Rotations#390]
This is the current list of maps on the Nostalgia Rotation. I have listed some complaints/improvements of each map that I hope is taken into consideration. Maps that I feel are perfect are labeled as "really no need to improve":

 - Fortress Battles : Really no need to improve

 - Medieval Warfare : This map is often rushed way too easily. A tactic often used by rushers is using the wooden bridges to get over  to the other team's side. Once there, they sprint across the sidings of the castle and can either blow up supplies inside the base or go for the core. An easy improvement would be to eliminate the bridges or lengthen the void gap.
 
 - Harb : Really no need to improve

 - Sky Traffic : Sadly this map is still quite laggy, especially near the back ship. I'm not sure how the lag should be fixed, so I suggest that Sky Traffic should no longer be in the rotations. Also, if I remember correctly, not to many "Nostalgians" were bothered the last time Sky Traffic was taken off rotations.
 
 - Spaceship Battles : Really no need to improve

 - Sand Wars : Really no need to improve. Although this map is very controversial to keep, I feel that it is a perfect TDM. You can kill enemies from a variety of positions; from above, below, behind, in front of. Maybe if the sand towers were shortened and there was a replacement for torches (maybe invisible blocks?), there wouldn't be many complaints of lag.
 
 - A Watery Grave : This is another Nostalgia classic that seems to not play well. It is often rushed and there is not much use for the TNT. If there are many defenders, the map actually plays sort of intensely. Defenders need to work hard to isolate the obsidian cube, remove water, blocks, etc. However, as we all know, the existence of rushers is little to none. It may be best to totally remove this map.
 
 - Race for Victory : Really no need to improve

 - Cake Wars : I really enjoyed the gameplay that Cake Wars TE brought into the tournament. The removal of floating cakes made for no easy rushing and block placing. Also having 1 strength pot made teams fight and use it tactfully. Finally, the saplings made for some further interesting gameplay and tactics. I believe that the improvements in Cake Wars TE should immediately be placed into Nostalgia.

 - Urban Jungle : Even with its recent change to being like PGM v1.0, the map still plays not so well. As usual, the team who has the Sharpness iron swords and iron armor dominate the map through spawnkilling and camping. The spawn is open to a variety of spawn killers, making it nearly impossible for an unlucky team to reach the objective. I think that Urban Jungle has ran its course on public rotations, and sadly should be taken out.

 - Airship Battle : Another map that often falls victim to rushers and carpet bombers. The propellers make it very easy to drop TNT on the majority of the ship, including the core. Some possible fixes include removing the propellers (just have floating ships like in Sky Traffic), create an obsidian ceiling above the core, or add more obsidian near the spawn tunnel. 

 - Shroom Trip : Another great Nostalgia map that gets rushed way to quickly. The middle mushrooms allow for rushers to quickly make it over to either the opposite spawn or core. A possible fix to this could be to totally remove the mushrooms (like how Cake Wars TE totally removed the floating cakes). By removing these platforms, I'm very interested on how the map could be played. Another problem with this map is that it is very easy to bridge from the 3rd mushroom to the core. A possible fix could be to shift the core a couple blocks closer to the 2nd mushroom (maybe a 7~10 shift). I feel that the 1 layer obsidian cube is pretty unique for the Nostalgia rotation, so it should be kept.
 
 - Avalanche : Finally, another map that also is widely rushed easily. Often players use the side obsidian islands to easily bridge toward the opposing team's side. Skybridging and camping / blockspaming near the spawn tunnels are other issues. I think that the side obsidian islands and the height limit are aspects of this map that are too important (or used too often it could cause upsetting). If I remember correctly though, the spawn tunnel can still be accessible by enemies. If this is the case, I feel that the entire spawn tunnel should be blocked from enemies.

Some Possible Replacement Maps for Nostalgia:

- Battle of Lyn-whatever : This map is a pretty cool TDM. It includes block placing, team pushes, and a wide vanilla-friendly landscape. However, most Nostalgians do not agree with TDMs on a widely known TNT/Core server. A cool edition to this map could be TNT, but this should definitely be tested first. 

- Fort Wars : A classic map that will need improvements if added again. Firstly, there needs to be either obsidian or bedrock underneath spawn and the castle. This way if TNT rushers destroy the base, players can actually escape from spawn. The minefield in the middle of the map, although a "staple to the original gameplay," has to go if added back. It allows for an extremely easy pathway toward the other side (the cobwebs prove no match for rushers by the way). A fix for this would be to totally remove the minefield and perhaps extend the void gap. (I forget how big the minefield is. If it seems to create a reasonably sized void gap, then keep it)

- Blocks DTC TE : Sort of forget if this is considered "Nostalgic," but would be a very cool edition to the map rotation. I, and most Nostalgians, would especially praise the map for not allowing tnt explosion in spawn / near spawn chests

My Suggested Rotation:

 - Fortress Battles
 - Battle of Lyn (Edited?)
 - Fort Wars (Edited)
 - Medieval Warfare (Edited)
 - Cake Wars (TE Edited)
 - Sand Wars (Edited?)
 - Spaceship Battles
 - Race for Victory
 - Airship Battle (Edited)
 - Shroom Trip (Edited)
 - Blocks DTC (TE)  

Some "In-General" Fixes:
In general, most Nostalgia maps get poor rating because of spawn killing. I can't actually think of a Nostalgia map were it is impossible to spawn camp (accept maybe Avalanche, however it is very time consuming due to the re-genning blocks). I think a very cool fix to this problem, which could also be used server-wide, is to send the player a warning if they are spawn killing. If the player is swinging/shooting/killing players ~1 blocks from spawn or has a piece of tnt land ~2 blocks from spawn, then a message should be sent to them:

! Spawnkilling is not allowed ; Please stop swinging your sword or firing your cannon toward spawn ! 

The idea at first glance, I can imagine, can seem pretty irritating / unrealistic. However, a message like this (which could translated into multiple languages) could be enormously encouraging to stop players who spawn kill. Like when TNT licensing was first tested on Primed and then introduced to the other servers, this idea should also follow the same path. It should first be tested on 1-2 servers and then distributed to the rest.  

24/7:
Although it is rude of me to suggest this, I do believe that Nostalgia should be back on the 24/7 block. With the above changes, I think that this rotation can be enjoyed by Nostalgians, Primed players, new players, or any players alike. 

How would something like this be done?
A lot of hard work from talented map makers would need to be put into an effort like this. Map makers would need to cleverly edit these old maps in a way to *improve the gameplay,* not merely change aesthetics. (Many "Nostalgians," as you may know, do not appreciate //replace wool stainedclay) 

Once changes have been made, the testing process is going to be equally as painful and annoying as the editing of the maps. Map makers would, of course, have to deal with the usual complaints and also investigate the gameplay of each map if the problems have been solved.

Where would something like this be tested?
There could be a couple of options for venues:

- An admin / moderator could place the edited maps into Nostalgia rotations for testing
- An admin / moderator could edit the original maps on Nostalgia using WorldEdit (would be time consuming and maybe impossible)
- An admin / moderator / map maker / map maker in residence could place the edited maps into a private server  
- An admin / moderator / map maker / map maker in residence could edit original Nostalgia maps on a private server and then test them

I just want to thank anyone who fully reads this awfully long improvement or "wishlist" for the Nostalgia Rotation. I have been playing on Nostalgia for awhile and I feel that the following changes could have a bright impact on old, new, and re-occurring players. Thank you for reading.

**Comment by 2000thehecf1** [comment]
I really think that Nostalgia rotation really needs to get an update. I know that the Nostalgia rotation is for the old maps, but I think that it could really get improved by getting more maps from since two or one and a half year ago. They're not very old maps, but I think that if we don't do this, Nostalgia will get more boring with the same 13 maps going and going again.

**Comment by CoWinkKeyDinkInc** [comment]
Fort Wars would also need more food than just a few stacks of apples and the few fish that you're lucky to get from the fishing rods.
One layer cores are also on SSB, and I think that Cake Wars TE would be a good idea.

**Comment by 2000thehecf1** [comment]
Bump? Nostalgia opens now frequently and I think this is important...

**Comment by Electroid** [comment]
We're going to fix/purge some nostalgia maps, but we have higher priority things right now. (Internal issue for this)
