### ISSUE TITLE
Improve Blocks II

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Rotations#391]
This map is bugged a lot. I just leaked the core, it didn't show any touch and it didn't count me on stats. There are some places where you can't place or destroy blocks like the TNT, the cake, etc. Pls fix it.

**Comment by matic0basle** [comment]
Bugs should be reported on the issue repo. This is a repo to add or remove maps from rotations. 

https://github.com/OvercastNetwork/Issues

When making an issue please read the README.md file before you make an issue.

**Comment by 2000thehecf1** [comment]
@matic0basle Oh, ok, sorry
