### ISSUE TITLE
Bring back those maps

### ISSUE THREAD

**Issue by MrTheSharpie** [OvercastNetwork/Rotations#392]
-broken unity
-4th Law
-viridun TDM
They were all good maps, I don't understand why did you remove them D:

**Comment by Ipskie** [comment]
Please make your titles and requests a lot more specific. Why do you want them back, in what rotations, where in those rotations? (Quoting ratings to back you up would also help). Also if these aren't all for the same rotation you should split them into separate issues.

For bullet points, please read https://help.github.com/articles/github-flavored-markdown/ to learn the flavoured markdown

**Comment by MrTheSharpie** [comment]
Closed. When I am at the PC I will make a new one.
