### ISSUE TITLE
Remove The Last Sunset from Broken

### ISSUE THREAD

**Issue by BlueManOtti** [OvercastNetwork/Rotations#396]
The gameplay of the map is horrible. Either the flags get painlooped with boats or the flags are that good defended, that it is nearly impossible to acces them.

**Comment by DoomRobotBoy** [comment]
From what I saw, the map plays fine. However, I haven't always been there to see how the gameplay averagely goes.

If either of your said problems are existent I can probably alter the flag islands to make them harder to rush and harder to defend (larger islands, but a better starting defense).

**Comment by oib5** [comment]
+1, the map is awful for CTF.

**Comment by DoomRobotBoy** [comment]
@oib5 Could you explain a bit further? I do have plans on updating the map and every piece of feedback is appreciated.

**Comment by BlueManOtti** [comment]
@DoomRobotBoy your ideas wont change much. The Last Sunset just plays like Sunrise Over Paradise before the monument modes were added to the map. Either it go rushed or so good defended, that it was nearly impossible to get the monument. Small changes wont fix the problem imo.

**Comment by DoomRobotBoy** [comment]
@BlueManOtti Whose talking about small changes. I am already gathering feedback to remake the entire layout.

**Comment by Oo-TheFrog** [comment]
Can this be closed? Its been removed.

**Comment by iPGz** [comment]
Closed as no longer applicable.
