### ISSUE TITLE
Remove The Complex CTF from Broken

### ISSUE THREAD

**Issue by oib5** [OvercastNetwork/Rotations#397]
The map is extremely difficult/annoying to navigate and thus not suited well for CTF, simple as that. Also covering the flag with leaves is stupid.

**Comment by DoomRobotBoy** [comment]
The navigating is not that hard after you played it one or two times. The only problem I see is that the map sometimes stalemates a lot, though that happens less then when it doesn't stalemate.

**Comment by oib5** [comment]
I wouldn't say that at all. The first few times I played it took about 3 minutes to bring the flag back because I had to turn around so much due to dead ends. That's not what a CTF should be. Taking maps and adding a CTF element without thinking much into redesigning isn't very effective, in most cases.

**Comment by ItzaMeLuigi** [comment]
I don't think you should be able to place leaves right around the flag.

**Comment by Z3R0Z3R0Z3R0** [comment]
@itzameluigi or right next to the portals

**Comment by CoWinkKeyDinkInc** [comment]
The map just needs to be more easier to figure out how to get to the flag, and maybe add more bridges to it.

**Comment by ItzaMeLuigi** [comment]
Adding on to my previous suggestion, I think it's unneeded to have walls up in the middle ring making it impassible.

**Comment by thestrangeboy1** [comment]
Removed. Low ratings after a while, especially comparing it to how high CTF maps are. Portals were always causing problems with camping and there's several other reasons as to why this should be removed.
