### ISSUE TITLE
Remove Aerst Grove from Conquer

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Rotations#398]
The map played bad from the moment it was added, here is a list of the issues:

- The great amount of leaves make the map very messy and laggy (for those with graphics: fancy, or not-great computers).
- Combat is difficult, the opposite of what the map should be (it being TDM). There are a lot of obstacles and holes, and its hard to even remotely find someone in this jungle of leaves. The map is cramped.

On top of above said, the ratings are pretty poor (3.43), not enough to keep it in the rots IMO.

**Comment by Tapetepato** [comment]
+1, Even tought i never play on Conquer, i remember playing this map 2 or 3 times, and finding enemies was really difficult, and chasing people was too confusing because of all the leaves and things.

**Comment by thestrangeboy1** [comment]
Removed.
