### ISSUE TITLE
Add Fort Beverstone to Capture servers

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#399]
https://oc.tc/maps/fort_beverstone
This map looks great, and it plays great too. I have played a couple of matches of it (it doesnt get /sn'ed that much) and its very good. Wools are not too easy to get like all the maps on the Capture rotations, and it doesn't end at 3 minutes. Since it's an Attack and Defend map, you can actually choose to defend and you don't have to be afraid of your own team rushing the game, because everyone knows that isn't fun for anyone except for the rusher. It is really different from all the other ctws on the capture server, and there isn't any woolroom so you can't hide there and killfarm. There aren't that much blocks on the spawnkit, and they're just leaves, so it isn't a mess of blocks of painloopy rushers, so it's much more enjoyable. It's actually challenging to get the wool, and defending is fun too, but not that OP. 
I really think you should give this map a chance on the rotations of both Capture1 and Capture2, since it would give people a break from the typical routine of Capture (fast bridge, fast blockspam, get the wool under 5 minutes, rush back, repeat)

**Comment by thestrangeboy1** [comment]
The original style of the map was intended to be like a CTF as there is no wool rooms but wool pads. I've tried converting it into CTF but at one point my server screwed up everything and I haven't gone around to fixing the remaining errors. Not sure if CTF will be mixed in with Capture, but if it does I'm willing to update this map to perfect it. Currently, there's no way I see it being in rots.

**Comment by Oo-TheFrog** [comment]
-1 The ctf version is much more fun.

**Comment by thestrangeboy1** [comment]
I have future plans for the map, but they won't happen any time soon. It's current state is not ready for public.
