### ISSUE TITLE
Remove Interitus from rotations

### ISSUE THREAD

**Issue by dentmaged** [OvercastNetwork/Rotations#400]
Interitus is a good map, however it is easily rushed. Within the first minute, you will find 2 - 3 armoured players on your side. Within the next 2 minutes, most of the enemy will be on your side. Take a look at this screenshot (below). This game lasted for 2 minutes and 39 seconds due to team stacking and rushing. We (blue) didn't get a single touch.

The team with more players has the advantage and on this map, has an even bigger advantage.

I still think that Interitus should still be in tournaments, but most certainly not in public games.

![](http://i.imgur.com/GURL90b.jpg)

**Comment by CoWinkKeyDinkInc** [comment]
Two extra people is now considered team-stacking?  The problem with this match is that it is being played with only about 15 players.  Stacking and rushing isn't something wrong with the map specifically, as plenty of other maps play with team-stacking and are rushed.
I think the solution here would be to bump up the players to 40, as I still think the map has too little players to prevent rushing or acknowledge rushing, I think a portal that allows you to select which side to spawn from, like cos(tnt) has may stop rushing even further.

**Comment by Tapetepato** [comment]
https://github.com/OvercastNetwork/Rotations/issues/356 Huge +1, this map is way too easy to rush and since Primed is always stacked, it's not fun to play

**Comment by dentmaged** [comment]
@CoWinkKeyDinkInc "Loads of players join one team, I join the other team (to try to make it fair), PGM automatically reorganises the teams, 10 donators on one team whilst the other only have 1 - 2 (including myself), donators run around objective and kill farming". And it is stackers and rushers, who will ruin Overcast (and already are). However, Broken is a good server to play on, it's relaxed and there aren't many rushers. However, I would still like to use 1.7.10 and play different gamemodes from time to time.

**Comment by CoWinkKeyDinkInc** [comment]
Donor stacking isn't something the map can fix, you said it yourself that this map is good, but the stacking is the bad part.  PGM just needs to be updated on how to balance players, and maybe disable joining specific teams after a donor stack is detected, and rein-able it when 40 minutes pass.  PGM needs to balance players more easier and the map to add more small features to make rushing harder.  For the times that the match was balanced and "fair", it isn't worth removing.

**Comment by thestrangeboy1** [comment]
^^^ #356 Duplicate
