### ISSUE TITLE
Add Limbo ll to the rot of Conquer , or in Mini

### ISSUE THREAD

**Issue by Axeeth** [OvercastNetwork/Rotations#401]
Hello I think , if you add limbo ll to the rotation of conquer would be amazing , because in conquest All the teams practiced on that map , because they liked it a lot , and it was my favourite map

**Comment by matic0basle** [comment]
Theres a difference between tournament and "public" play. Tournaments have communication between teammates and are more strategy based.

This is a good map for tournaments but I don't think it will play that well on public servers.

**Comment by Tapetepato** [comment]
-1, I remember the map being /sn some times, and it played really bad. It's too cluttered and small, and i don't think it would play well in the public rotations

**Comment by Ipskie** [comment]
As stated, tournament maps don't necessarily make good pub maps, this is a good case of that, primarily due to it being very small. Conquer no, but in a mini it might be good actually

**Comment by thestrangeboy1** [comment]
The map was designed with rotating in mind which requires a lot of teamwork to handle, and with the points so close to each other and to spawns, you have no time to communicate nor would it be worth it. It's a constant painloop to which ever hill you'd like to go to. I know this is an enjoyable map to the competitive players, but it's best if it stays in Ranked for the time being.
