### ISSUE TITLE
Add Zap to Primed rotation

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/Rotations#402]
Add Zap to Primed rotation

**Comment by Brettogden** [comment]
Yeah, It's in the works but I need to finish the map. I would say it's 90% done right now.

**Comment by Z3R0Z3R0Z3R0** [comment]
Zap is not fit for primed. The gameplay isn't tnt focused, and it does not use tnt well. The tnt is a side goal, and thus it should not go on primed.

**Comment by Ipskie** [comment]
I agree with HIVE, the map is not fit for primed rots

**Comment by ItzaMeLuigi** [comment]
Zap is just a cannon killfarm. Aim your cannon at the beginning of the bridge and constantly fire.

**Comment by Tapetepato** [comment]
-1, as Z3R0 said, this is not a map that would fit on Primed.
It's basically and spleef game, and there's barely any cannon made that can help the map, since sides are too far away. If anything, it should be added to Arcade when it comes up.

**Comment by Oo-TheFrog** [comment]
-1 I agree it doesn't fit primed

**Comment by Pablete1234** [comment]
primed is basically anything that uses tnt, and for cores we have DTC, i think primed should be based arround the "cannoner kit", and maps like boom box, ender blast, cos(tnt), Zap, Kï, and clay-based maps are the most suitable for it

**Comment by thestrangeboy1** [comment]
Map has been removed from the repo, it's going to be remade sometime.
