### ISSUE TITLE
Remove unless Improved Wintery Cabin from Alpha Rotations

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Rotations#403]
Even though the map's rating is above average (3.74) I still think this map, in its current state, does not belong in the rotations.

The map is incredibly hard to defend:

Both the monument and core are in a valley, making it far more easier to attack than to defend the objectives. This makes attackers able to access the monuments from all directions (it being closed in by multiple mountains), and to access the core from the mountain behind it. 

Whilst defending I had no idea there were 2 guys on the core, I mean they could literally come from anywhere, and to make a defense while constantly looking around to see if no one is coming is not doable. Of course looking around is a standard with defending, but because they can so easily sneak past your team's front liners, you can know all to well that they are coming.

Extending on above, the center is way too easy to rush. Players just sky bridged to the side-mountains and went on from there. The center of the center is hardly used, because everything happens on skybridges there. The center is quite useless currently it being overrun in seconds.

However, because the matches do seem to last a good while (5minutes minimally) and the ratings are quite good, it may be better to keep this map but just fix the 'problems':

- Make the monument and core position more open (away from mountains). Reasons explained above. I also think the current positions of the objectives are quite hard to be found by those willing to defend it.
- Make the center lengthier and possibly with more obstacles (referring to mountains or rivers; structures that slow players down), it doesn't hurt if the rushers need more time to rush.

**Comment by Ipskie** [comment]
I support this: the objective placement, especially of the core do not facilitate or encourage defense at all

**Comment by Tapetepato** [comment]
I really like this map, even tought it doesn't come up into the rotations that much at the hours i can play, the few times i have played it, it was well defended, or just because of the size, the terrain, the middle island and other things, the matches lasted for more than 20 minutes.  I think that maps that are easy to defend, and that actually get defended should still be on the rotations, since there are really few of maps like this, so -1

**Comment by DoomRobotBoy** [comment]
> I think that maps that are easy to defend, and that actually get defended should still be on the rotations, since there are really few of maps like this, so -1

I just wrote an essay about why defending is impossible here, and than you disagree with the removal because it is too easy to defend? ;-;

**Comment by Tapetepato** [comment]
@DoomRobotBoy maybe not "too easy" but i still think it's not that difficult to defend there

**Comment by Ipskie** [comment]
@Tapetepato likely the only reason the map isn't over lighting fast is because of its size and how long it takes to get to the enemy side

**Comment by yoyopower** [comment]
No longer relevant.
