### ISSUE TITLE
Remove Wrath Altar

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#404]
It seemed like a fun map at first, it's pretty big and it looks good, but it plays really bad.

The spawnresistance is too long, so people can just pearl from spawn or spawn path to the middle without getting killed. Because of the way the map is made, and because of the issue i mentioned before, its 100% a fight in the middle of the map. No one evers uses the sides of the map, even tought it is pretty big, people just pearl outside from spawn and hope to not die from a guy waiting where the enderpearl falls. Basically, you just throw a pearl there, kill one or 2 guys, and then someone pearls into you (sometimes even with spawnresistance still on them) and get killed, and this is how it plays for the whole 9 minutes.

**Comment by thestrangeboy1** [comment]
Removed.
