### ISSUE TITLE
Update Rooted to v1.1

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Rotations#405]
**Update**: *Rooted v1.1*
After a while I've decided to update Rooted as it is in the repository. The "while" is standing for 8 months, a long time. I entirely redesigned the map with a more natural theme, it turned out great. The layout didn't really change:

- Fixed a small issue in symmetry
- 2 blocks longer wool-room lanes
- New spawn-lane

Some other changed I've done (with matic0basle):

- New Spawnkit
- Different wool-room loot
- Improved bedrock-barrier
- Thicker Soil
- and more...

In general we tried to improve the gameplay, all in all there are less obstacles etc.

**Links**
- [Download](http://www.mediafire.com/download/6l2rhn6qgl6okdq/Rooted+v1.1.zip)
- [XML](https://gist.github.com/rockymine/05af1f21456119e2a53f)
- [Pictures](http://imgur.com/a/AtHMZ)
- [Old](https://oc.tc/forums/topics/54041cb167d5225b0e008387)

*Thanks for reading!*

**Comment by rockymine** [comment]
**Using 1.8 Blocks!**

**Comment by mrapple** [comment]
This goes on the Issues repo
