### ISSUE TITLE
Add Battleship Halberd?

### ISSUE THREAD

**Issue by skippy369** [OvercastNetwork/Rotations#408]
https://maps.oc.tc/Mixed/Standard/Battleship%20Halberd/
https://oc.tc/forums/topics/543b1d055f35b9d664001743?page=1#543b1d055f35b9d664001742
https://oc.tc/maps/battleship_halberd

**Comment by Ipskie** [comment]
Please remove the question mark (proper syntax and all that)

I don't particularly like the map, it has the rush flaws of SSB and none of the vigilante nostalgia that has kept SSB in rots

**Comment by DoomRobotBoy** [comment]
Even though I love the map I do not think it is fitting for any rotations. It may be very open, but the player flow is not guided through the map that well. I can hardly get out of the ship x)

I still think it is a great map for /setnext events.

**Comment by Electroid** [comment]
We've tested it many times, it isn't going to work for pubs. We would have added it a while ago if it did. It suffers from many issues that Nostalgia maps have.
