### ISSUE TITLE
Add SolitudeMC and Desert Cataract to Mini01/02 Rotations

### ISSUE THREAD

**Issue by MrBloxley** [OvercastNetwork/Rotations#409]
These maps have extremely high ratings (with respective ratings of 3.85 for SolitudeMC and 3.89 for Desert Cataract). These maps are loved in the community and Desert Cataract used to be in the rotations for one of these servers, but is no longer. Mini01/02 are the only mini servers open in the evening/early night for us on the west coast and it would be greatly appreciated if we could play our favorite maps.

**Comment by Tywnis** [comment]
I'm working on an update to mini rots, and your feedback will be considered.

**Comment by matic0basle** [comment]
SolitudeMC already has a separate issue with a lot of replies.
https://github.com/OvercastNetwork/Rotations/issues/359
