### ISSUE TITLE
Relocate TF2: Badlands in CTF rotation

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Rotations#410]
I don't know if I can post such issues here, but it felt kinda unnecessary to post it on the forums;

I think it would be better if TF2: Badlands could be relocated to one of the earlier spots in the rotations. Currently it is in-between Koi and The Last Sunset on place 15. I feel like placing it somewhere on spot 1-5 would fit the player counts better. Koi is a 24v24 player map and The Last Sunset is a 22v22 player map. TF2: Badlands with the small player count of 10v10 doesn't leave much player for The Last Sunset which harms the quality of the gameplay on that map.

I hope this could be considered, thanks for reading.

**Comment by Ipskie** [comment]
Would upping the player count be bad for the map? That's one alternative

**Comment by DoomRobotBoy** [comment]
I don't know. TF2: Badlands is pretty balanced with classes as it is and adding more players would probably harm it more than it will do good. Like now each class has a certain percentage of players to it (most of them use scout) and with 10 players all with the class scout and thus speed, the map will just become another rush map. I can't however tell what will happen though.

**Comment by thestrangeboy1** [comment]
Done. ;)
