### ISSUE TITLE
Add Abudor 2 on Conquer

### ISSUE THREAD

**Issue by Timothee38** [OvercastNetwork/Rotations#411]
It got removed with the removal of KotH and I believe, due to the ratings and some feedback from other people that it was somewhat enjoyed by the community.

Any oppositions to this?

**Comment by Tywnis** [comment]
It's considered too big for minis, but i will consider it for an update to Conquer.

**Comment by Timothee38** [comment]
Allright, thanks!

**Comment by thestrangeboy1** [comment]
Added to Minis for now, when conquer receives another update I'll be sure to make this happen as well if needed
