### ISSUE TITLE
Add Citadel

### ISSUE THREAD

**Issue by Diamyx** [OvercastNetwork/Rotations#412]
Citadel is a map that underwent many changes through residency based on community feedback. Although the ratings may seem a little shaky, we feel like it would bring something new to the Mini rotations and that it should be considered. Map Residency has helped us get Citadel to the point where we're confident that it would fit in the rotations. https://oc.tc/maps/citadel

**Comment by matic0basle** [comment]
Its a really nice map with quite balanced gameplay. Should be added. "+1"

**Comment by Ipskie** [comment]
I'd like to see this tried out in rots too

**Comment by yoyopower** [comment]
I've played this quite a lot and it's a good map. I agree with the addition.

**Comment by DoomRobotBoy** [comment]
I agree with this addition, its a fun unique map with new features and a big-ass pirate ship. +1

**Comment by rockymine** [comment]
It's definitely worth adding. It's really amazing, not just gameplay, also aesthetics.

**Comment by thestrangeboy1** [comment]
Added.
