### ISSUE TITLE
Temporarily remove Antiquis if not updated

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Rotations#413]
This is already an issue but the map is affected in a big way with this issue. You break one block and your pickaxe becomes useless.

I have tried what CoWinkKeyDinkInc suggested and no luck with multiple tries. I am not sure if its fixed in 1.8 PGM but if not it should be or the map should be temporarily removed.

https://github.com/OvercastNetwork/Issues/issues/1612

While this is an issue that should be fixed the map should be updated to use "Live Gear" where instead of getting the stars, your gear would update on its own through streaks set in XML. Since you can craft the wooden pickaxe thats not needed in the XML.

So if this issue is fixed or close to being fixed please do it as soon as possible because the map is affected in quite a big way by this. If a fix is not so near completion then please adapt the map and use the live gear system where the pickaxes would upgrade on their own.

**Comment by 2000thehecf1** [comment]
This is already fixed (https://oc.tc/forums/topics/55774aed5f35b97ae3000bdb?page=1#557775d367d522ce62001eee), so you can close it.
