### ISSUE TITLE
Move Spaceship Battles' position in the Primed Rotation

### ISSUE THREAD

**Issue by Cevans98** [OvercastNetwork/Rotations#415]
Well yeah, it's after Cos(tnt) and the two maps that follow it are Boom Box and Ender Blast, which sucks as I literally have to cherry pick the time that I can play Primed, as I leave whenever any of the "Tnt run, chaos cannon, quartz and clay" maps come around.

Also, the gameplay on SSB struggles as a result. Who can blame people griefing and chaos cannoning when the map is after Cos? 

I ask that it gets put within range of the classic DTC maps.

**Comment by MobbareKurtZ** [comment]
I agree with this. Maybe there should even be a "gimmicky" primed server and one for "real" maps.

**Comment by nygiants10** [comment]
I thoroughly agree, I hate that my favorite map, cos(tnt), is followed by SSB, which I despise for its crappy gameplay on pubs. It sucks having to wait through SSB or just leave while I wait for better maps like BoomBox or Ender Blast to come on.

So while I have a much different perspective than you, I agree that similar maps should be kept together in the rots.

**Comment by MobbareKurtZ** [comment]
@nygiants10 Actually, cos(tnt) have one of the worser gameplays. It's all about tnt spamming and chaos cannoning. SSB can be really fun if you actually defend. Not to mention, cos(tnt) is pretty much destroying primed, new players learn to do chaos cannons and then doesn't care on other maps if the ground isn't regenerating or if there already is a real cannon right next.

**Comment by Ipskie** [comment]
@MobbareKurtZ This is not the place to bash cos.

OP, I agree, the rotation makes Primed feel like it has bipolar disorder from the drastic stylistic change

**Comment by Cevans98** [comment]
yo it's been like 2.5 months, any response?

**Comment by thestrangeboy1** [comment]
Primed is merged with Destroy so the placement of SSB would need a separate issue if you disagree with it now.
