### ISSUE TITLE
Add Outback to Capture Rotations

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Rotations#416]
![outback](https://cloud.githubusercontent.com/assets/8013626/7921852/9da10fc4-08a8-11e5-854c-d292d4486a89.PNG)

Outback is quite an old map. It took a very long time to make it work nicely, but now it seems to be ready.

*Comment with your Thoughts below!*

*Rocky*

**Comment by thestrangeboy1** [comment]
Keep it to #387
