### ISSUE TITLE
Add New Server for Testing or Add More Maps 

### ISSUE THREAD

**Issue by DreaD4m** [OvercastNetwork/Rotations#417]
I was thinking that some of the maps were overplayed, and less people join to that map,
I think we need to change many rotations.
Many maps on oc.tc were unrated, so we don`t know about what maps are popular to change our rotation. 
Go here and see how many maps were unrated. https://oc.tc/maps/all
We can change our rotation or make a new server to see what maps are interested by people, and change the entire rotation.
(I`m not american or english, so my language can be strange a bit :( )

**Comment by matic0basle** [comment]
>A request should add or remove a single map to/from the rotations. Multiple changes require multiple issues. Changes to server names and other suggestions belong on the forums, not here.

Also I think you can't see the ratings of maps until they reach 300 unless you are the author and also if the map hasn't been played since the ratings were added to the website.

I think a server change is needed but not what you are describing.

**Comment by DreaD4m** [comment]
I didnt know about that :( 
I was just posting about every things...
sorry.
