### ISSUE TITLE
Remove Harb

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#419]
Out of the Nostalgia rotation, this is definetly the worst map (if we don't count99% of the rushed matches on the other maps ofc).

It looks somewhat good, but it's gameplay is really bad. In my opinion it is the worst TDM (without counting Ragetdms) on the rotations. 
The TNT is a good thing, but sometimes, it won't help on situations like when you are being followed by the whole team, it takes too long to blow up, i suggest change it to maybe half of the time. The map is 40v40, but when Nostalgia is online, it plays at around 10v10, and even if it's some kind of party, it plays at 20v20. Also, when someone racks up a ton of it, they just go to spawn and use it.

On matches with such a short ammount of people, it is really difficult to be with one teammate on the same place. They are all scattered around the map. The fact that the map has a ton of buildigns, stairs, fences, wall and things like that, make it really anoying to pvp, and people will often jump around and corner you on a rooftop or on a corner between two buildings. 
The main 2 paths infront of spawn are too small and it usually ends on people placing the tnt they spawn with and hope they get a kill.
I don't really know how to describe it, but the way the map is made is just not enjoyable to play. It feels clustered, and sometimes a team will entirely dominate the other one. If you are in the losing team, or just on a team with few players, you most likely wont get more than 1 kill before dying. It's really clustered to go around this places, and people can get lost easily when chasing someone. Also, the fact that you can't place TNT on the bases is really confusing, i don't see why you can't place it at the very back or in the main paths as long as it isn't in a house or the actual spawn. And, why can you break blocks? I have never seen this used, and i feel like it's an unecessary feature that people often use to pillar up, hide (on the blitz version), or just do nothing because they don't even notice.

I know that because it is a nostalgic map no matter how broken it is it isn't supposed to be removed, but i'm pretty sure maps like Fort Wars or Sky Traffic got removed for a reason.

**Comment by nygiants10** [comment]
Nostalgia is the graveyard for bad maps though.

In all seriousness, I think Harb has decent gameplay. I've always found it enjoyable to run around and make people chase you or hop on roofs. The buildings and close quarters make PvP a bit more strategic, and it becomes a lot easier to use the map to your advantage (getting people trapped in corners, using roofs to get height advantage, etc). The TNT is harder to use because of the long fuse, but this fits somewhat well with the Nostalgia idea of maps with more "vanilla" mechanics. Harb seems to be fairly well liked among regulars, and its rating (3.59) is the second highest on Nostalgia.

**Comment by CoWinkKeyDinkInc** [comment]
Harb is great, it's fun to make tiny little cannons on the map and run.  It's fast, although I wish the map was bigger.

**Comment by statcoman** [comment]
I think it's time to put this map to rest.  It's just bad in general and
the gameplay is incredibility bad.

**Comment by matic0basle** [comment]
Harb is a fun little map with fast gameplay. Should not be removed IMO

**Comment by itsmartin** [comment]
Still enjoyable, and I think it plays well. I feel like it still has its place in the rots. Currently on both conquer and nostalgia, though.

**Comment by TheMolkaPL** [comment]
I like Hard, really. It's gameplay is very fun because of TNT and many ways.

**Comment by ItsMiiOlly** [comment]
Nah
