### ISSUE TITLE
Remove Battle Ecliptica CTF

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#420]
The original version of the map promoted defense, since it was really easy to break and you could make really great stuff with just slabs. But now, this version doesn't have that. You can't even break blocks, and you don't even get blocks as a kill reward.
Adding renewable blocks completly defeats the purpouse of defending, and its just not fun anymore
You get attacked by the front, and the sides, and even if you defend with the small wall you can only make with your spawnkit, you will lose, because it doesn't work like the original version.
I suggest that it should be changed to be like the CTW one, when once a team captures one, they cant capture it again and first to cap the 3 wins, even if it isn't 1 cap of each per team to win, make it so the team that wins can cap multiple times, but only win if they cap 1 of each team.

I don't see why this got changed, if i remember correctly it was like the normal BEII before, and this change made it even worse than the TE edition. I read in chat or on the forums that the map was made this way to encourage defending, but really, how do you do it if you get barely any blocks, you can't break blocks, and you can loose even if no one gets into your flag room?

**Comment by amactus** [comment]
I agree and disagree with this. I like how it is time limited but I think it does need to be changed. Regenerating blocks makes tunneling and defending impossible and the side connections need to be shorter to make attacking harder

**Comment by Electroid** [comment]
The renewables algorithm was changed, it isn't as vigorous anymore with `interval`. The no kill reward blocks must be a bug, I'll look into that. I also made changes to this map that will be on pubs very soon.
