### ISSUE TITLE
Add Masarin II to Destroy or Alpha

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Rotations#422]
Plays good its a fun nice map, I would like to see it added.

**Comment by DoomRobotBoy** [comment]
It stalemates a lot as of currently. The core is compared to the distance 'enemies' have to travel way too close to spawn. This causes major misbalance and with a decent set of defenders the map can take hours.

**Comment by Oo-TheFrog** [comment]
@DoomRobotBoy I'm looking at the recent matches and the average match length is about 20 minutes.
