### ISSUE TITLE
Add Ki back to primed

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Rotations#423]
I would like to see Ki added back to the rotations with a few changes:

1. Make it you can't icarus or bridge only cannon
2. Remove the water like in DATAstation
3. Get rid of the dispensers
4. Make the void gap bigger

**Comment by Ipskie** [comment]
With some changes it could be suitable, but until those are made, no

**Comment by Electroid** [comment]
Not applicable anymore.
