### ISSUE TITLE
Change or Remove Directrix

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Rotations#424]
This map stalemates to much, it needs changed or removed. My idea is to add a 15 minute timer and the team with the most caps wins or we add a 5 second respawn timer.

**Comment by kroest** [comment]
i think the average game on it is like 15 minutes, which is fine for me. in my opinion, directrix is pretty much the best ctf map at the moment, and should not get removed from the rotations.

**Comment by Brettogden** [comment]
Electroid updated the map today, and it seems to fix this issue.

**Comment by Oo-TheFrog** [comment]
The issue isn't fixed. Please reopen this.
