### ISSUE TITLE
Remove Irongate Harbor from rotations

### ISSUE THREAD

**Issue by koipen** [OvercastNetwork/Rotations#425]
As the author of the map, I'd like to remove Irongate Harbor from US Alpha rotation and all other rotations where it may be.

**Comment by CoWinkKeyDinkInc** [comment]
The map is well received by many people.  Why would you want it removed?

**Comment by koipen** [comment]
It is never played at its full capacity as I intended. I'm removing it from the rotations until Alpha regularly gets over 50 people (that is, half the capacity) on matches.
