### ISSUE TITLE
Remove Levels

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#427]
This map was recently added to the rotations, with the Summer rotations' update, but it's gameplay is disastrous.
First, the map is too small, and people spawn on the spawn-room with the portals. When you go to the bottom, you usually find iron (some people don't but it's pretty easy), but when you go to the top, spawn with absolutely no armor. The void gap it's too small, same with the gap between the two plataforms.
 In a couple of minutes, or even seconds, there  is a staircase, and a ton of bridges around it. The fact that it's pretty small makes it really easy to rush, and since it's a straight line, people will usually blockspam their way to the woolroom. The fact that the map is small makes it even easier to do this, and it turns into a boring blockspam-painloop type of map.
When people rush by staircase, they go often to the top plataform, with iron armor, and easily kill the newly spawned players, that spawn with no cover and with no armor at the middle of nowhere. This makes it easy to killfarm, especially with the iron swords, and even more with the woolroom gear. Just like the bottom plataform, it get's covered in blockspam. 
It often has people confused all over the place, both attacking players and  normal players, about where to place the wool, where's the iron, how to get back to the other level, and other things, resulting in even more blockspam; and a bunch of random pillars.

**Comment by Oo-TheFrog** [comment]
+1 I agree with your points.

**Comment by ItzaMeLuigi** [comment]
This map either needs to be removed or updated. I was making a defense and the game ended because apparently you can go from one wool room to the other. It's basically impossible to defend.

**Comment by yoyopower** [comment]
Removed
