### ISSUE TITLE
Add Checkmate to Primed rotation

### ISSUE THREAD

**Issue by koipen** [OvercastNetwork/Rotations#428]
I've been setting this map a couple of times now on Primed, and the response has been generally very positive. It's fresh and new and would make a good addition to the rotation.

It still might need more testing and I feel the map could be further developed (for example, experimenting with an attacker - defender set-up).

**Comment by Z3R0Z3R0Z3R0** [comment]
Has it undergone major changes recently? I remember playing it a while back and the gameplay was pretty bad.

**Comment by 2000thehecf1** [comment]
I played it this morning for the first time and I really liked it. The only thing that I disliked was the wool monument place, it's a little difficult to find, but I agree with the adition +1.

**Comment by DoomRobotBoy** [comment]
I agree with its addition :+1: The layout works great and nearly every layer is used. Should also be quite simple to understand, so all in all a fitting map!

**Comment by Electroid** [comment]
The project is abandoned at this point.
