### ISSUE TITLE
Make Sweet Tooth FFA

### ISSUE THREAD

**Issue by amactus** [OvercastNetwork/Rotations#429]
The rage map Sweet Tooth is in my opinion, too large for a team map. It is difficult to find enemies and in general very annoying. Making it a OITC FFA (rage bows, normal swords) would make it more interesting and give it much better gameplay

**Comment by matic0basle** [comment]
This repo is just for adding and removing maps to and from rotations not for map requests. You should talk about that with the map maker.

**Comment by Ipskie** [comment]
But dax is dead

**Comment by Oo-TheFrog** [comment]
This was ment for rage tdm not rage, on a side note I have been working on a ffa version of it.
