### ISSUE TITLE
Add Safehouse to Mini's

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Rotations#431]
Its a fun fast nice map and could fit in the rotations after xyth ctf.

**Comment by matic0basle** [comment]
I am not against this but IMO (as the author) I don't think a 5v5 would fit in that nicely. Thinking on the bigger picture here since the map can hold such a small amount of players.

**Comment by Tapetepato** [comment]
No. Too small, there's isn't much to do and it's really easy to cap.
