### ISSUE TITLE
add koi back to the ctf rot, since the map got fixed

### ISSUE THREAD

**Issue by kroest** [OvercastNetwork/Rotations#432]
https://github.com/OvercastNetwork/Issues/issues/1923

on this issue i requisted my map to get moved out of the ctf rot untill it got updated, but they forgot to add it back after updating it.

**Comment by Brettogden** [comment]
https://oc.tc/forums/topics/5580610d67d5223f75001b8f

**Comment by Tapetepato** [comment]
+1, its really good, it's fun to defend it with the wood, and matches usually last for a good time (15-20+minutes). Definetly one of the bests CTFs

**Comment by kroest** [comment]
koi should be moved to be after palace in the ctf rotation, since palace is the biggest map after koi in the current rotation, and the ctf rotation is ordered in the player limits of the maps.

**Comment by Brettogden** [comment]
Done.
