### ISSUE TITLE
Remove DATAbasin until improved

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Rotations#436]
This map is broken, the kits are to overpowered the cannoner kit doesn't even have a pickaxe. Its never a close game if your winning its a blowout.

**Comment by amactus** [comment]
I totally agree but removing it is not the answer, IMO the archer & defender class needs nerfing and the cannoneer class needs a pickaxe

**Comment by Z3R0Z3R0Z3R0** [comment]
@amactus Then remove until improved

**Comment by statcoman** [comment]
The map is just bad in general.  Limited teamwork is even considered by the players and its just a race to see who can get more of the dam.  

Please remove this horrible map.

**Comment by Oo-TheFrog** [comment]
Anyone against removing this until its improved?

https://oc.tc/forums/topics/549df39ac296359b480003dc
https://oc.tc/forums/topics/55317f6367d5220f280085cc
https://oc.tc/forums/topics/55e7fbe1c29635c7b7000072
https://oc.tc/forums/topics/54c1a34d5f35b941830014de?page=1#54c1b0775f35b972dd001515
https://oc.tc/forums/topics/5443a9335f35b916f70005bb?page=1#5444044bc2963588d100114c
https://oc.tc/forums/topics/54cc08c867d5222e52000f09?page=1#54cc280fc29635af7e0015c4
https://oc.tc/forums/topics/551e7f585f35b999980021bf?page=1#551eb48ac296354cf5001ee0
