### ISSUE TITLE
Remove/Fix Ring Race

### ISSUE THREAD

**Issue by PoseidonsM** [OvercastNetwork/Rotations#437]
http://puu.sh/iXlog/5c4d9ab0b9.png

Unsymmetrical void gap both sides. Yes it is a big deal. Yes it matters. Fix for OCD.
Thankyou. I love you.

**Comment by minimitch0199** [comment]
This is not the correct repository for this kind of issue. Please recreate this under [OvercastNetwork/Issues](https://github.com/OvercastNetwork/Issues/issues/new).
