### ISSUE TITLE
Remove Iris DTC from primed

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Rotations#438]
This map gets rushed all the time. TNT isn't used in the map much, you will see a few cannons at the beginning but after that everyone just rushes. Its the worst rated dtc map.

**Comment by Tapetepato** [comment]
-1 It's my favorite DTC map, and i haven't seen it rushed that much, it's fun to play, and it has more cannoning than other maps like SSB or Interitus

**Comment by statcoman** [comment]
Yes, this is a very good idea.  Usually this map is rushed in under 5 minutes with the non stacked team offering little to no resistance.  Its not fun at all for new players.  

+1

**Comment by thestrangeboy1** [comment]
Removed.
