### ISSUE TITLE
Remove Lost World: CTF until imbalances are fixed

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Rotations#439]
The imbalances are described here: https://oc.tc/forums/topics/558307fcc296356f11004acd. Red has a clear disadvantage and imo this map should be temp removed until said issues are fixed.

**Comment by Oo-TheFrog** [comment]
Yeah this should be removed until its fixed.

**Comment by yoyopower** [comment]
I think the map is still fine for public play, in a tournament setting this would be terrible but on pub it's not a huge problem. If the rotation ever receives a large update this will be considered.
