### ISSUE TITLE
Remove Diversity 

### ISSUE THREAD

**Issue by iKingie** [OvercastNetwork/Rotations#442]
This map is one of the worst maps in the rotations. You get barely any wood and the blocks dont drop when you dig out a pit, making it nearly impossible to defend unless you have a coordinated team.Also sorry if this isnt how you adress this sort of thing but its my first time. Thanks!

**Comment by Oo-TheFrog** [comment]
+1 I agree, its nearly impossible to defend.

**Comment by yoyopower** [comment]
The ratings are good and matches seem to be capable of lasting a good time. This will not be removed right now.
