### ISSUE TITLE
Remove Viridun or fix it

### ISSUE THREAD

**Issue by BlueManOtti** [OvercastNetwork/Rotations#443]
I really like Viridun. It is a really cool map with a lot of secret chests. A huge aspect of the map was that you were able to enchant and to brew potions. Since the 1.8 you aren't any longer able to enchant on this map.
Also the potion filter (at least that's what I think it is) removes bottles automatically  which means that you can't brew any longer because you don't have any bottles.
Without these secrets the map looses a lot of its charme.

**Comment by Electroid** [comment]
We'll fix it, but no need to remove.
