### ISSUE TITLE
Remove DATAstation on /server Primed

### ISSUE THREAD

**Issue by statcoman** [OvercastNetwork/Rotations#448]
The map in case you didn't know is a breeding place for farmers and stackers on both US and also on EU.  The map encourages very little teamwork and if you are not on the side that has the most donators you generally lose.  

Overcast Network is a "team-based" server.  DATAstation encourages the very opposite of that.   Bassicly the whole map is a farm for people that know how to cannon and new players are thrown into it without any knowledge of how it works and are taken advantage of.  

Thank you for your time.

~Statcoman

**Comment by thestrangeboy1** [comment]
Removed.
