### ISSUE TITLE
Remove/fix Hot Dam

### ISSUE THREAD

**Issue by Statcoman** [OvercastNetwork/Rotations#452]
The map "Hot Dam" is a great map.  I love playing on it.  But the problem is how short the matches are.  There is no way to set up a defense because of the amount of diamond rushers.  What I would suggest adding to the map would be the following:

>Bedrock core mode for the first 5 minutes of the match

>Better iron pickaxes and axes to clear up block spam

>Add a spawnkit that includes the following: Food, Wood, diamond sword and tools.

>A longer strength potion effect after respawning to prevent spawn camping and so at least some defense can be created or perhaps adding resistance potion effect to newly spawned.

I'm not saying that this is a bad map its just needs some improvement.  

Thank you for reading.

-Statcoman

**Comment by Tapetepato** [comment]
+1

**Comment by thestrangeboy1** [comment]
Removed for now. I'll see if I can edit it in the future or get Nada to do so.
