### ISSUE TITLE
Remove Desert Sanctuary

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#453]
After playing a few matches and watching another few, i can safely say this is the CTF with the worst gameplay so far. A team always dominates a whole match. Once a team gets the flag for the first time and holds it for more than 20 points you know they won. The 3 flag spots make it even worse. 
For example, there's a team gest the flag and go to their spawn. then they all die and they respawn, and the other team rushes the spot where the flag spawns, but then they all die  at the first second and the other team stays  there, gets it and then goes to spawn, gains a lot of points, and then the flag spawns in the middle. After a bunch of painlooping that team gets the flag and gains a lot of points again. Since it's only on Ranked rotations, people leave and aren't able to join, so if there's an experienced player (or a cheater, those guys play a lot of this type of maps), and the other team is 1-2 players down, they lost. It's a bunch of painlooping to get the flag and to kill the flag carrier, and the fact that there's a long respawn timer and a  long flag timer makes it feel like we are playing a KotH map, wich is a bad thing.

Suggestions to fix it:
Remove the respawn timer
Make the flag timer shorter (5-8 seconds instead of 20)
Give full health to the flag carrier
Remove it and add a better KotF map, The Grove or Concourse would do great on Ranked.

**Comment by yoyopower** [comment]
The map is doing fine. If you still feel this map needs an update make a post on the forums.
