### ISSUE TITLE
Add Sunrise Over Paradise to Ranked

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Rotations#455]
It is an excellent map for Ranked as it almost always needs teamwork to get to the monument from the boats, land or the sky-bridges.  The only problem I see is the map constantly reaching the time-limit, but I haven't played that map in a while.

**Comment by DoomRobotBoy** [comment]
Having the monument made out of something like Beacons would work better if SoP were to be on Ranked. Players on ranked know how to defend and beacons still take a while to mine. I don't think you would even need any monuments modes if the monuments were beacon from the start.

**Comment by thestrangeboy1** [comment]
Done.
