### ISSUE TITLE
Remove Xyth CTF

### ISSUE THREAD

**Issue by BlueManOtti** [OvercastNetwork/Rotations#457]
This map would probably fit very good into the arcade but not on "normal" servers.
You can fly around all the time and you got a paintball gun that one shots everyone. 
I think the concept of the map is funny but it doesn't fit into Mini-Rotations at all.

**Comment by Z3R0Z3R0Z3R0** [comment]
Agreed, it doesn't have any gameplay features that are remotely similar to any other map on the network.

**Comment by yoyopower** [comment]
Removed
