### ISSUE TITLE
Remove NextGen

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#458]
I know this map is supposedly good in tournament gameplay, but in public one it feels like an even more rushable version of RFV2. It isn't an improved version, it's a more difficult to defend and extremly easy to rush one. It has the same blockspam problems, but a lot of stuff is easier (getting into the wool, via rush by blockspam, or by a short skybridge from the roof, etc.) This is a big problem given on how a lot of people can click ridiculously fast nowadays and thus making it really difficult to counter. Honestly, the concept is good, but if you are adding a map like this to ranked, just add RFV2.

**Comment by ItsMiiOlly** [comment]
What does everyone else think? It's only been added for a couple of hours - I think it would be best to wait for a couple of days to get a good verdict on it.

**Comment by Z3R0Z3R0Z3R0** [comment]
@ItsMiiOlly I wonder if removing the top of the roof automatically would help?

**Comment by 2000thehecf1** [comment]
Maybe lowering team sizes back to 10 might help.

**Comment by DoomRobotBoy** [comment]
Lowering team sizes would probably fix a lot @ItsMiiOlly 

Quoted from my post on the 'Ranked Rotation' Thread:
> Can you lower the team sizes from the current (12v12) to lower (10v10). Basically Nextgen now has like 10 attackers and 2 defenders on each team instead of the usual 8 attackers and 2 defenders, meaning defenders have to fight off more enemies. Not to mention that not every game has such amounts of defenders.

**Comment by ItzaMeLuigi** [comment]
NextGen should definitely be a 10v10. Not sure why it's the only map in the rots to have 2 extra players on each team. I also think the roof at the top should be removed to help out defenders a bit.

**Comment by thestrangeboy1** [comment]
NextGen is now a 10v10. It plays a bit better now and we still may edit the map in the future as the roof has been a known problem. For now, it plays fine in Ranked.
