### ISSUE TITLE
Add Long Shot to Alpha's or CTF's Rotations

### ISSUE THREAD

**Issue by KasiCrafter** [OvercastNetwork/Rotations#459]
Long Shot is a 25 vs 25 map made in the often forgotten RFV style. Each team is tasked to build from checkpoint island to checkpoint island to reach their flag, which they will then have to run back to base, doing so twice to win. Once the flag is dropped by the flag carrier (who has slowness and reduced HP), there is a minute long cool down before it respawns, meaning teams with good offense are rewarded.

In most other PGM maps, such as in CTWs, single players usually make or break the match, completing the objective by themselves. Long Shot, however, requires a lot of teamwork to win. Players must construct bridges, reinforce bridges, run the flag, destroy enemy walkways, and snipe enemy flag carriers; tasks one player cannot do alone. Flag carriers are extremely vulnerable, so players will have to escort them as they run all the way back to spawn, meaning that even the person completing the objective is relying on their team to win.

imgur album: http://imgur.com/a/AJDT4#0

**Comment by Z3R0Z3R0Z3R0** [comment]
Played this map a bit ago, basically seemed like a race to click (autoclick) as fast as you can in a race to bridge to the flag and run back, avoiding a very difficult long distance shot. Gameplay will be almost identical every single match, with very little room for diferentiation.

**Comment by Oo-TheFrog** [comment]
Yes please, it plays very good and you need teamwork to win.

**Comment by yoyopower** [comment]
Alpha currently does not exist and its size is too different for any of the capture servers. It works well as a set next map. I'd consider making either a smaller version for the capture 2/3 rotation, I'd happily test/add it for you if you made it.
