### ISSUE TITLE
Make each Ranked rotation different

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Rotations#460]
So I've been watching today as how Ranked was working, and as well as Golden Drought III is always played, some other maps are never and just being cycled over and over. This makes that just a few maps on the Ranked rotation are played at the end of the day. As I've seen SSB TE uses to be played, and the reason it does is only because it comes right after GD III, because, for example, BE CTF hasn't been played on the entire day until it has been setnexed after GD III. So that's why I suggest you to make every Ranked rotation to look different, such as Beta and Alpha are, you will make people to play more variety of maps, and not just their favorite map and the one that comes next (they will do, but at least the map that comes next won't be always the same.)

**Comment by thestrangeboy1** [comment]
The order of maps won't make a difference due to the fact that you can skip them all. We've edited rotations so that there's maps that are played often on the rot. If it's not getting played, people just don't enjoy playing it.
