### ISSUE TITLE
Update Diversity to V1.5

### ISSUE THREAD

**Issue by CeFourC4** [OvercastNetwork/Rotations#463]
Recently I updated the map to improve the gameplay and make it harder to rush. The XML works fine  and here is the link; 
http://www.mediafire.com/download/4td433jgrrxjrv5/Diversity.zip

Changes:
Thinner wool lanes
Axe and more wood included in spawn kit
Bedrock wall changed to prevent circle jumping
Iron moved to the middle of the map
Spawns moved further back
6 diamonds per side.

**Comment by mitchiiii** [comment]
Wrong repository, map updates are to be created under [Issues](https://github.com/OvercastNetwork/Issues/issues).
