### ISSUE TITLE
Add Concourse to Ranked

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#464]
I mentioned earlier (27 days ago) https://github.com/OvercastNetwork/Rotations/issues/453 that desert sanctuary should be removed: it honestly gets decided in the first 1-2 minutes and plays really bad.
There, i suggested that it could be replaced by Concourse, but i did not give much reasoning (also, that issue has no replies in almost a month for some odd reason...)
I also made this thread to suggest stuff for ranked, where i suggested some maps for a rotation, but since i posted it on a time where no one is online on the forums (unsure what time it was, but it was around afternoon in my country Mexico). https://oc.tc/forums/topics/55d61d325f35b927fc0010e9?page=1#55f5ae6e67d522a953001f62
So anyways, im making an issue for this map, because i honestly thinks its great.
"Concourse: The best KotF. This is by far better than the thing we currently have on ranked (desert sanctuary). Here you can actually kill the flag carrier, since they get low health plus the map is really open. Matches are always balanced with close endings, and since it's open, there's a lot of bow action wich is always great. This could replace DS on Ranked."
My feedback from the thread.
One could argue that it would be a waste of a match because there's not an objective to get in your stats, or even a flag to cap, but this is the exact same thing that happens with desert sanctuary and some people still play it, so i don't see anything wrong with a kotf added to ranked.
As i said before on those two links, DS gets decided in the first minutes of the game, sometimes even during the team huddle when you see a team has got 1 or two players that click faster or that just are extremly experienced at the game. I have seen plenty of people complain about this exact same thing and this is why its skipped sometimes, but it's still there. This map would be great replacement for that one, and heres why:

The map is balanced: Unlike DS, you actually can do something on this map to turn the match around. It's less cluttered, and also smaller, so a push to the flag is actually possible, and with 1 or 2 competent players, you can get the flag carrier with your bow.

Also, here there isn't a trouble to get the flag after the other team had it, since the places it spawns are wide open and easy to reach. The way the map is made actually gives both teams a chance to win and to have fun. It's open for bowing, and players can actually get the flag, 
When a player gets the flag, he can easily get killed in 2 shots or hits. and then it can spawn right there on the side spawners, but people still have a chance to get them, and they still can hide behind those little walls that provide good but not ridiculously big cover, and they can still run around the map if they need to. 

I think overall,  this map has everything that DS lacks as a KotF and i think it would be very enjoyable to have at Ranked.
Toughts?

**Comment by yoyopower** [comment]
This map is not currently being considered for ranked as the current tournament based rotation works well. I think a better place for a discussion on the ranked rotation would be on the forum thread.
