### ISSUE TITLE
Change Ranked Rotation

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Rotations#466]
The maps that are played the most are Deepwind Jungle, GD III, Fractal Descent, Next Gen, and SSB TE.

The following maps are barley played and should be removed:

Aerolock
Antiquis TE
Retaliation
The Fenland CTF
Justice
Directrix
Streamline
BE CTF

I didn't post a reason for why each map should be removed because I think the match list under the maps page speaks for itself. Some of these maps haven't been played more than 4 times in 3 weeks.

I would add Super Cube, Ring Race, and Concourse.

Super Cube is a great map it plays good and I think it could work on ranked with a few changes/tests.

Ring Race is a good map its like any other ctw I don't see why it couldn't fit ranked.

Concourse https://github.com/OvercastNetwork/Rotations/issues/464

**Comment by yoyopower** [comment]
Made a chart/graph thing a few days ago to look at the ranked rotation, I agree with the removals.

https://docs.google.com/spreadsheets/d/15zQjzRPWuwTRsrHR4HILzingEjVeYDuY5N3FOQIUUxg/edit?usp=sharing

**Comment by Oo-TheFrog** [comment]
Gonna close this now that the rotations are changed
