### ISSUE TITLE
Remove Storm from Conquer eu

### ISSUE THREAD

**Issue by McFanta** [OvercastNetwork/Rotations#469]
Many people on europe is like never playing conquer specially i dont see that often storm has been played so why not replace storm with rift that would change a lot of things! Hope you guys liked this idea!

**Comment by thestrangeboy1** [comment]
https://oc.tc/matches?server_id=524cb26fe3e3562d0d9a9d28

Conquer on EU is barely played with low player counts and it ends up being that you'll only be able to play a 5v5 on the few "favorite" maps for TDM/KotH. Storm is a great map and was one of the first KotH maps we've had on our network and with a good rating of 3.68, I don't see the point in removing a classic as there are barely any problems with the map. Middle point is almost always contested and the side hills are great for small fights (3v3s) when the map can be at least half full. Storm will stay.
