### ISSUE TITLE
Add Crippled Divide to Ranked

### ISSUE THREAD

**Issue by McFanta** [OvercastNetwork/Rotations#470]
It would be fun to see Crippled Divide on ranked!
Reasons?

Well in my opinion mixed maps on ranked is very fun to Play and i have played the map i want on ranked twice and its really enjoyable so i hope you map devs could add Crippled Divide to ranked it would be super awesome to have it on ranked!

**Comment by thestrangeboy1** [comment]
The map is way to big for Ranked as the maps on Ranked are meant to be 8v8-12v12 where as this map can fit a 50v50. 3 objectives that are spread out wouldnt work if the map was condensed too and the front line would be such a pain to hold because of how wide it is.
