### ISSUE TITLE
Remove RFV2 from Capture

### ISSUE THREAD

**Issue by Oo-TheFrog** [OvercastNetwork/Rotations#471]
The gameplay in RFV2 is broken, players can get both wools by just getting into one room making it impossible to defend. The ratings are some of the worst at 3.55

Its also a very small map for 64 players.

**Comment by Statcoman** [comment]
Its a good map, but it does need some fixing.  

+1 for remove.

**Comment by McFanta** [comment]
+1 Mate!

**Comment by Zenzoh** [comment]
+1, replace with NextGen (no te)
