### ISSUE TITLE
Remove SuperCUBE from Ranked servers

### ISSUE THREAD

**Issue by EyQu** [OvercastNetwork/Rotations#474]
After looking on ranked servers, when this map cycles, no one wants to play it and (the majority) of people don't join and wait for it to cycle to another map.

Although I think this map is decent, I don't think it's good for the ranked servers, and looking at feedback from players in game, they seem to agree.

**Comment by AnthonyTag** [comment]
yeah probably worth removing

**Comment by Oo-TheFrog** [comment]
I made a forum topic lots of people agreed with removing it, justice, and be ctf.

https://oc.tc/forums/topics/561a90e4c2963516aa000660

https://github.com/OvercastNetwork/Rotations/issues/473

**Comment by statcoman** [comment]
Please do so, barely anyone plays on this map anyway when it comes around in the ranked rotations.

**Comment by Oo-TheFrog** [comment]
Its gone
