### ISSUE TITLE
add Facility TE and Aaeros to the ranked rotation

### ISSUE THREAD

**Issue by JanPaulMosterdijk** [OvercastNetwork/Rotations#476]
i feel like these maps would really fit the ranked rotation, and would add some more variation to them, since it currently mostly consists out of CTW and DTC/DTM maps. 

- Facility TE is one of the best tdm maps there is, and really fits the player count. the rotation misses a good tdm map.
- Aaeros is one of the most fun KoTH maps on the server, and would suit the semi- competitive ranked servers. The rotation does not have a KoTH map yet, and i would like to see how Aaeros would play out on the ranked servers.

edit: what about replacing Justice with Ubos CTF?

**Comment by yoyopower** [comment]
TDM on ranked will not work, the matches can be decided by just getting one troll/bad player on your team. Limbo has been added as a KoTH. Justice is also no longer in the rotation.
