### ISSUE TITLE
Remove Deepwind Jungle from Ranked

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#478]
This map is terrible and not a single match plays well. It's really difficult to defend and play as a team on a ranked gameplay, since most of the time if not all the time people don't want to play as a team. All it takes it for the unbalanced team selecting system to put 2 of the typical ctw offenders on a team and its basically  a gg.
https://oc.tc/matches/5623c083c8f2afb474d8b0c7
https://oc.tc/matches/56225ff5c8f2d33cfec84ec9
https://oc.tc/matches/562282dec8f20e74608a3080
https://oc.tc/matches/56224696c8f2356bfe8a3e5c
https://oc.tc/matches/56217acac8f26bcae850a54e
https://oc.tc/matches/56216f5fc8f26bcae850a1e9
https://oc.tc/matches/56213347c8f26fc001baed93
https://oc.tc/matches/56211432c8f22cd4bb5f9320
Those are just some of the matches from the last 3 pages of the matches at Ranked 1 (3 days). There are even more like that on other servers and on other days, all of them last less than 10 minutes, most even less than 6. I just played a match that lasted 1 minute with 37 seconds, and it played like this: No one on my team said anything on the team huddle (as usual) and then all of my team went to rush. Same with the other team. They had 4 on one of our wool in the first 30 seconds or less and in 10 more they were already at the other wool. Our team had touches on both of the wools on around the same time. After that it was basically a painloop and a race to see who placed them first and who won. Most of the matches play like this. It's such an easy map to rush and it's the map that most of what you would call objective farmers play. You can see that this even affects maps before it on the rotation, BE II, wich is a great map that often gets close to play but gets skipped because of the people yelling "WAIT DJ". So, since it's a typical tourney ctw it attracts those players, and of course they're not going to defend, so most of the games end like this, a lot of painloop with touches on 3-4 wools at the first minute and after that a painloop at the wool to push the attackers back or painlooping at the middle to stop them from getting into their base.

If not, there are plenty of 12-15 minute games. On this ones, there's usually a defense on at least 1 wool on each side. Since you don't get arrow kill rewards, or a better axe, players will eventually get into every wool with one simple 12-cps staircase, and after that it turns into a painloop battle just like every other game. Cleaning blockspam and bridges is extremly hard as a defender, because the axe is a really bad one. There's also the bridging from the islands. It's a ranked game, so of course you won't get 1 defender for each wool and 1 defender to destroy each island. obviously, with 2 or 3 attackers that know how to bridge, there's going to be a stair from that island, and after that it's pretty much impossible to stop it, all you can do is go to the island and destroy 5-6 blocks before they come back and hope that holds them back for enough time.

And there are the ones that last 15+ minutes. Those ones are once again the same, sometimes with a more skilled defender. On these ones there's the blockspam problem too, and of course the one of the stair from the island. Even if these things do not work for them to get into the wool, they're going to be there, everyone uses it. Skybridge are used on these "long games". One team gets a guy to staircase and then do a fast no-shift bridge or something and they're over the enemy team. As i said, teams are usually unbalanced on ranked, so a lot of times because of lack of organization there's a skbridge on only one team and after that it's one team getting completly dominated. Even when both teams get a skybridge, there will be a lot of painlooping and constant fighting on the skybridge, and with the usual guy with more knocback that normal, one can take the skybridge in a second and then dominate the other team. Either way, every match is full of painlooping. Once the skybridge is over the stair of the other team it's pretty much over. You can get 2 guys shooting skybridgers off but if the enemy team is smart they will send about 4 offenders to skybridge to extend it fast.

Overall, the whole game is constant fast bridging both staircase and skybridge, and painloop from both teams to get into a wool or to kill the guys in a wool. Again, bridging is a big deal that decides games because axes are really bad and you get few arrows.

-------------------------------------------------------------------------------------------------------------------------------

Now, i'm not sure if i can give suggestions for you map makers can make this map  playable here on github, but just in case, these are my suggestions.

-Give a better axe (at least iron axe with efficiency II)
-Give a 8-10 arrows kill reward.
-Lower height limit.

With these easy fixes you make it possible to take out a bridge, and even if there is, it can still be easier because of the lowered height limit. If not, this map deserves to be removed completly.

If you for some reason refuse to remove it, the least i can ask is for you to move it from the rotation. As i said before, people skip the only (good) ctfs on ranked; BE II and Justice, because when these come in a lot of ctw players hop into the server and start saying "WAIT DJ WAIT DJ WAIT DJ". I think it should be moved either between Golden Drought III and Space Ship Battles (because these are both maps that have a somewhat decent gameplay and are played a lot, so there wouldn't be the risk of people skipping them to play Deepwind Jungle) or right after Space Ship Battles for the same reason, people wouldn't skip those 2 maps to play deepwind, and since the ctf maps would come after it, people wouldn't feel the need to skip it.

**Comment by ItzaMeLuigi** [comment]
Even with the TE edit, it's still way too easy for attackers to get into the wool rooms. The map is balanced for teams that defend, but almost no one does in public. I would suggest removing the islands on either side of the map to make it a lot harder for an initial rush giving people who do defend enough time to actually set one up.

**Comment by Oo-TheFrog** [comment]
Its gone.

**Comment by thestrangeboy1** [comment]
andddddddd it's outta here!
