### ISSUE TITLE
Add The Nile on Destroy US & EU

### ISSUE THREAD

**Issue by Guicotsch** [OvercastNetwork/Rotations#482]
Title says it all. It was removed and can only be found on Alpha right now. Think it's a great map that could be added back to destroy servers.
Thanks.

**Comment by elephantLocator** [comment]
:+1: 

This is a great map, and games on the alpha server do not really do it justice, due to the low player counts. I would be very happy to see it on destroy.

**Comment by McFanta** [comment]
:+1:

**Comment by barneygale** [comment]
+1

**Comment by thestrangeboy1** [comment]
Added.
