### ISSUE TITLE
Remove Halfway Home

### ISSUE THREAD

**Issue by orky48** [OvercastNetwork/Rotations#483]
It has a average rating of 3.57 current version and plays awfully. 

You spawn above the monument which means trying to get there by ground is so much more difficult because if you kill someone on your way to the monument they will respawn right above it knowing you are there. 

The map at most is 4 blocks thick with a void gap between monuments/middle making tunneling impossible. 

The only reliable way to get the monument is via a sky bridge or the other team just being bad. If you want to make a defence you hinder your teams ability to leave spawn unless you capture the hill which is nearly impossible to get back once the enemy has it as they can just respawn there. 

Also the aesthetics are atrocious.

This map is quite simply not fit for public play

**Comment by thestrangeboy1** [comment]
Removed for a while, forgot to close this.
