### ISSUE TITLE
Remove An Overcast Christmas 

### ISSUE THREAD

**Issue by McFanta** [OvercastNetwork/Rotations#484]
The gameplay isn't really good, the map is a huge chokopoint for players. The enchantment system is just chaotic. This doesn't deserve to be in the rotations.

Regards

McFanta_

**Comment by Oo-TheFrog** [comment]
-1 Its a christmas map thats in the rotations for the holidays, I find it very fun. I also think gameplay decent.

**Comment by McFanta** [comment]
@Oo-TheFrog It is but it has some issues though. So for now, I will be closing this and then ask a map dev or the author to update it.

**Comment by Oo-TheFrog** [comment]
Please list reasons for why it needs to be updated.
