### ISSUE TITLE
Remove/Edit Deepwind Jungle

### ISSUE THREAD

**Issue by ItzaMeLuigi** [OvercastNetwork/Rotations#489]
All matches of Deepwind I see last 2 minutes max. It's way too easy to rush and shouldn't be kept in the rots in it's current situation. I would suggest removing the two side islands to make it harder for people to get across easily. It would be great to see this in the tourney version too so we can get it back on Ranked.

**Comment by yoyopower** [comment]
It's a popular map with an above average rating in the rotation it is in. While the map could be better it willl not be removed at the moment.
