### ISSUE TITLE
Update RAGE 

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Rotations#492]
I know RAGE isn't the most popular thing but quite a few players still play it and it shouldn't take long to update.

Add:
Sand Wall
Network
The End
Cubed3
Hanging Garden 
Hand Of God
Wonderland 
Trinity
Milky Way
Fallen Empire
Rig
Chinatown
Bouncy Stadium

Remove:
Sweet Tooth - Too big atm. 
Zen - Bad ratings (3.48).
Secluded Wharf - Bad ratings (3.48).
Vine Bay - Bad ratings (3.52) and its to easy to camp.
Deschutes - Poor aesthetics and boring gameplay.
Pride - Bad ratings (3.43).
Lush - Bad Ratings (3.48).
Java - Its easy to camp in this map and it has bad ratings (3.43).

**Comment by AnthonyTag** [comment]
Thanks for the suggestion! I agree, it's about time for an update. I'll get working on something now.

**Comment by AnthonyTag** [comment]
Made a few updates...will make a post now with some explanations. Thanks again for the suggestions!
