### ISSUE TITLE
Update Destroy 

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Rotations#493]
Add:

Blocks II - Its easy to defend and has good ratings(3.68).
Astro - Easy to defend, hard to rush, and has good ratings(3.68).
Masarin II - Just a good map besides the fact that it takes players a couple minutes to reach the core.
Irongate Habor - Fun hidden chest, and players love to defend it.
The Nile - Alpha is dead atm so it only gets about 5 players per match.
Avalon Funland - same reason as The Nile.
Midnight Train - see above.

Remove:

SSB- I know its classic but it plays pretty bad.
Iris - Very bad ratings(3.23).
Sky Traffic 2 - Very hard to defend and bad ratings(3.46).
Aerobellum - Bad ratings(3.49).

**Comment by amactus** [comment]
I really like SSB, and it plays pretty well for public when compared to most Primed maps

**Comment by elephantLocator** [comment]
I'm going to support removal of Sky Traffic 2, hard to defend, hard not to get TNT spawnkilled over and over.

Midnight train gets a big :+1: from me.

**Comment by iPGz** [comment]
I also support the removal of Sky Traffic, I feel Destroy should become a lot more noob friendly.

**Comment by yoyopower** [comment]
An update is being worked on for destroy, all discussion related to the update should go in the thread here: https://oc.tc/forums/topics/5739ca6267d522371d000002
