### ISSUE TITLE
Revamp Mini01 rotation

### ISSUE THREAD

**Issue by MrTheSharpie** [OvercastNetwork/Rotations#496]
I sadly think that the actual Mini01 rotation isn't the best it could be. The problem is, you have full matches on objective maps and then when the TDMs/some CTFs come up a lot of players leave. I think a rotation made up of mostly ctw (like mini02 EU a year+ ago) plus a few DTC/M and maybe Directrix would have a fuller servers. What happens is that most of the time a TDM comes up people either disconnects or moves to capture.

Suggested rotation: 

- Fox Mini, Dynamo, BE2, Placid Spring, Cargo, Empire, Deepwind Jungle, Persisto, Woolirium and Infernal Shadow would make imo for a good CTW pool in the rot. 

- Then for DTM I would recommend Coastline, Snowy Wars, The Fenland (maybe Fenland CTF idk), Desert Cataract, Balloons DTM and Warlock. 

- For DTC, Tanker TNT and Thorns would be good (there aren't that many mini DTCs). 

- For CTF Directrix is good because it fast paced and I noticed people don't leave as much when it comes. 

Thoughts? I haven't really considered if the maps are in other mini rots because well, the only mini that's ever open is mini01.

**Comment by elephantLocator** [comment]
#495 I'd like to see Desert Country in the rots too.

**Comment by amactus** [comment]
I liek

**Comment by yoyopower** [comment]
Revamped it, revamping included feedback gave here.
