### ISSUE TITLE
Remove Alien from Micro

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Rotations#498]
Alien is the exact opposite of what a micro map should be. It's a kill steal fiesta because of how open and small it is.

**Comment by samthecat** [comment]
I agree, the general consensus while playing this map is that it is too cluttered, and that seem to almost always be in a 2v1 or worse. Atlas had originally agreed to fix that, but seeing as he's currently inactive,  I'll remove this from the rotation.
