### ISSUE TITLE
Remove Citadel from Capture2

### ISSUE THREAD

**Issue by Seode** [OvercastNetwork/Rotations#501]
This map empties servers. Each time this map plays, Capture2 goes from having 30 players on to having only 15. No good map does this.

**Comment by nygiants10** [comment]
I have seen this as well, whenever Citadel comes on, people leave. At an average rating of 3.39, it's the lowest rated map on Capture2 by .14 points, and is the lowest map on either capture server. It's just not a very well liked map.

**Comment by yoyopower** [comment]
Removed.
