### ISSUE TITLE
Update Capture 2 

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Rotations#502]
Remove:

Levels - Pain to defend and bad ratings(3.57).
Citadel - Very bad ratings(3.40), players just dislike this map.
Banana Split - Almost impossible to defend and bad ratings(3.55).

Add:

Connect - Unique and has good ratings (3.70).
Desert Country - Easy to defend on and  great ratings (3.77)

These may need a few tests but i think they could be added:

Drastic Change
Rooted

**Comment by yoyopower** [comment]
Keep it to one post per map update. Citadel is removed.
