### ISSUE TITLE
Adding Escensio back to Destroy

### ISSUE THREAD

**Issue by jochemboon** [OvercastNetwork/Rotations#504]
Escensio was a very good DTM map, please add it back to the Destroy rotation.

**Comment by yoyopower** [comment]
The ratings are terrible. The map will need editing for it to be added back.

**Comment by jochemboon** [comment]
I got it set a few times and people generally reacted postively, I can't imagine the ratings being terrible,

**Comment by yoyopower** [comment]
The rating is currently at 3.38. While it wouldn't be the lowest map in the rotation it is still really low for a potential rot map.
