### ISSUE TITLE
Adding Temple Valley back to Destroy

### ISSUE THREAD

**Issue by jochemboon** [OvercastNetwork/Rotations#505]
I remember Temple Valley being very popular when it was still in the rotations, I would favor this map over maps such as Royal Garden DTC. Please add it back to the destroy rotation

**Comment by ZacharyPylypuik** [comment]
WOW, nice shit post. Everyone knows that Temple Valley was hated, Royal Garden DTC is a much higher rated map, therefore better.
![936](https://cloud.githubusercontent.com/assets/8905745/17249474/219dee24-556e-11e6-91ee-798661816a73.jpg)

**Comment by yoyopower** [comment]
The map is too big for the current average player count on destroy, the ratings are also on the low side.
