### ISSUE TITLE
Add Coral Reef to destroy

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Rotations#506]
I originally made this map for the Destroy Rotations update but since thats no longer going to happen I was wondering if you could please add it to destroy.

Its a pretty solid map. 

- Its really hard to stalemate but easy to defend (Average match length is about  18 minutes).
- It has great aesthetics.
-  Rushing is tough but it can be done.
- It has great ratings (3.90) with about 85 ratings.
- Overall gameplay is almost perfect.

(https://oc.tc/maps/coral_reef)

**Comment by yoyopower** [comment]
Added
