### ISSUE TITLE
Edit Sky Traffic 2

### ISSUE THREAD

**Issue by PoseidonsM** [OvercastNetwork/Rotations#510]
Make spawn-killing harder on sky traffic 2: perhaps by adding some resistance or a spawnkit (and editting existing chests). Had to endure a 15m killing spree on the entire blue team which saw the numbers drop from around 10 to 3/4.

**Comment by mitchiiii** [comment]
Closing as this isn't the correct place for this kind of issue. Spawn killing related issues should be directed to this thread, however this specific case has been noted and methods to further prevent mass spawn killing will be looked into.
