### ISSUE TITLE
Add Sky of Ruins to Destroy

### ISSUE THREAD

**Issue by master00ofdsiware** [OvercastNetwork/Rotations#512]
People seem to like this map. The ratings are at 3.83, with 213 votes. Match times are usually between 8 and 22 minutes, with the average being about 15 minutes. It's unique in many ways, but gameplay is still very good.

(https://oc.tc/maps/sky_of_ruins)

**Comment by GoldenOre** [comment]
-1 Gameplay isn't that good/fun when i've played it, its mostly just skybridging. The map is very confusing with the portals. Furthermore its aesthetics are poor imo.

**Comment by master00ofdsiware** [comment]
"Confusing" - most players seem to understand it after a bit. Even looking at it in spectator mode (which many do) helps a ton.

"Mostly just skybridging" - Not so much. For the upper level, skybridges are frequently used, but not all the time. And skybridges for the lower level are very difficult to maintain.

"Poor aesthetics" - That is your opinion. I personally disliked Coral Reef's aesthetics, but I am not against it being in the rotation.

**Comment by GoldenOre** [comment]
"Mostly just skybridging" - Not so much. For the upper level, skybridges are frequently used, but not all the time. And skybridges for the lower level are very difficult to maintain.

False. I’ve watched quite a few matches and it’s all just painlooping sky. No defending, etc.
Summary of a match on Sky of Ruins: 
1 Minute in: https://gyazo.com/639e7b706c47a086ba4a86adda484a92
No one is defending or even walking around. Players are just skybridging.
3 Minutes in: https://gyazo.com/d37b87407ec95539d185906a59b63909
Again no one is defending or even walking around. Players are still just skybridging.
4 Minutes in: https://gyazo.com/3a058b1153af59d17c10b501c4b5f650 
It’s a ghost town, no one is defending or doing much of anything at their base besides skybridging. 
5 Minutes: https://gyazo.com/5fb81fd39433473737fcbc9e5be32f64 https://gyazo.com/fa5e25326bab78f8e578679e35e7e09b 
Both monuments are now gone, no one was defending. Players are still skybridging.
6-9 Minutes in: https://gyazo.com/785c6372ffc0ee0008f8ecc8a3d6d433 https://gyazo.com/e75ef762b47e113b456c0c04571cf4a5 
Players are still bridging and the cores are untouched.
9 Minutes in: https://gyazo.com/09d16ec7a1c8a8f2f59f6ae12737b51f 
A few players chase someone on red to their core and try to kill him, they fail and the match ends. 



"Poor aesthetics" - That is an opinion, and it should not be the deciding factor in anything. I personally disliked Coral Reef's aesthetics, but I am not against it being in the rotation.

I agree having good gameplay is more important than having good aesthetics but Sky of Ruins doesn’t have either of those things. Buildings have no depth, the pallet is bland and boring and there is no real theme.  I’m also not sure why you even mention that you personally disliked Coral Reef’s aesthetics seeing that they clearly aren’t bad. (This is a fact.) Compare this map to any map in the destroy rotation and you will find that it lacks aesthetics.   


I’m also not sure why players die from instant damage potions when they fall into the void. You don’t get kills when you knock someone into the void.

**Comment by master00ofdsiware** [comment]
ogel, you might have never seen one of the matches that gets defended. An example is https://oc.tc/matches/57e5e32bc8f28a1a2b0189aa. I don't have photos but it played well.

Also, the potion thing is easily fixable.

**Comment by master00ofdsiware** [comment]
Closing this issue until I fix the problems mentioned above (except maybe the aesthetics, which are a subjective opinion.)
