### ISSUE TITLE
Add Blocks CTW to Capture

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Rotations#514]
Its a really fun map imo. Average match length is like 10 minutes. You can do a lot on the map whether its building defense, making redstone contraptions, farming xp in the wool, etc.

**Comment by 2000thehecf1** [comment]
Imo, defense should be nerfed, as there's only one way to enter the wool and height limit is too low it's really easy to defend and with a simple defense you can get a 1 hour match which makes no sense.

**Comment by master00ofdsiware** [comment]
Here's a video of typical Blocks CTW gameplay. Seems alright.
https://www.youtube.com/watch?v=poMmCSCLSQc

**Comment by yoyopower** [comment]
Added for now.

**Comment by 2000thehecf1** [comment]
From what I've played, it's easily stalemated once you enter the woolroom and gets boring. There should be gapples so that you don't have to be everytime going back to the chests of the woolroom to take health potions
