### ISSUE TITLE
Add SolitudeMC V1.3.5

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Rotations#521]
SolitudeMC has been updated to include some bug fixes and minor improvements. The download link is available in submissions on the forums.

The map has good ratings and it would be great if it could be readded to the Mini rotations.

**Comment by yoyopower** [comment]
Reopen this after it is updated and you get at least one playtest in.

**Comment by yoyopower** [comment]
This will be considered after the Halloween event is over (as there's a Halloween version of this map in the rotation currently).
