### ISSUE TITLE
Add SpOOky Diamonds to Mini

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Rotations#529]
SpOOky Diamonds is a map with decent asethetics and unique gameplay. Its already in capture3 but it doesn't get played much seeing that capture3 is dead.

**Comment by master00ofdsiware** [comment]
When I requested a setnext for Chocolate Diamonds, a lot of people complained that they didn't like it. Is the Halloween one better?

**Comment by GoldenOre** [comment]
Same version as the halloween version. I'm not sure why people would shoot down a map that they haven't played. It was set twice about 10 months ago and its only got 25 ratings.

**Comment by yoyopower** [comment]
It seems to be getting played a fair amount on capture 3, is this really needed?

**Comment by GoldenOre** [comment]
I'll close this now that ctf is alive again.
