### ISSUE TITLE
Add Celestial Twilight (Halloween map) to Destroy

### ISSUE THREAD

**Issue by master00ofdsiware** [OvercastNetwork/Rotations#530]
It was loaded quite late, but Celestial Twilight is a Halloween version of Sky of Ruins. Please add it to Destroy for the remainder of the Halloween rotation period.

[https://oc.tc/maps/celestial_twilight](https://oc.tc/maps/celestial_twilight)

**Comment by yoyopower** [comment]
Try to get at least one test of the map done, if there's no bugs I'll add it.

**Comment by master00ofdsiware** [comment]
@yoyopower It was just played. There were no bugs.

**Comment by yoyopower** [comment]
Adding it to destroy for the rest of the event.
