### ISSUE TITLE
Add Smoke to Ranked

### ISSUE THREAD

**Issue by nygiants10** [OvercastNetwork/Rotations#543]
I think Smoke could make for an interesting Ranked map at least. People seem to really like 5CP and PvP oriented gamemodes right now, so I think it would end up fairly popular.

**Comment by triplezko** [comment]
![](https://i.gyazo.com/754fbcf1765747d199232882e082f9e1.png)

Match ends way too quicker around the 1-2 minute mark, maybe even less.
